import publicDemo from './public-assets.ts'

export default {
  publicDemo,
  eyebrow: 'Your object workshop',
  title: 'From a product to your library',
  description: 'Paste a link, add the details and create a 3D object using the available dimensions and references for your project.',
  connection: { generationDisabled: 'Generation is disabled for this account. You can browse your library and use it in your projects.', checking: 'Connecting to the workshop…', online: 'Workshop connected', offline: 'Workshop disconnected', reconnect: 'Reconnect', offlineHelp: 'The workshop service is not responding. Try again later; if the problem continues, contact the administrator.', login: 'The AI service is unavailable. Ask the administrator to check its configuration.', blender: 'The 3D modelling service is unavailable. Contact the administrator to check the workshop.' },
  form: {
    title: 'Create an object', subtitle: 'The product page is the starting point.', url: 'Product link', urlPlaceholder: 'https://www.ikea.com/…', invalidUrl: 'Use a public http or https link without credentials or custom ports.', notes: 'Details and preferences', notesPlaceholder: 'Colour, material, product variant or details you want to preserve…', dimensions: 'Known dimensions (optional)', dimensionHelp: 'Outer dimensions in centimetres. Fill in all three or leave them empty to use the product page.', width: 'Width', height: 'Height', depth: 'Depth', submit: 'Create 3D object', sending: 'Sending…', footnote: 'Generation uses OpenAI and consumes credits from your account. Files are generated on the server and saved in your private library.', invalidDimensions: 'Enter width, height and depth between 5 and 2,000 cm.', created: 'Request received. Follow generation in the activity panel.', requestFailed: 'We could not complete the request. Please try again.',
  },
  jobs: {
    title: 'Workshop activity', empty: 'Your next creations will appear here.', cancel: 'Cancel', retry: 'Retry', answer: 'Add information', answerLabel: 'Your answer', answerPlaceholder: 'Clarifications, measurements or product details…', continue: 'Continue generation', view: 'View object', queued: 'Queued', analyzing: 'Studying the product', needs_input: 'Waiting for your answer', generating: 'Modelling in Blender', completed: 'Object generated', failed: 'Generation failed', cancelled: 'Cancelled', busy: 'Updating…', questions: 'Before continuing', untitled: 'New object',
  },
  activity: {
    title: 'Live generation', history: 'Selected creation', newObject: 'New object', view: 'View activity', intro: 'Follow each step here: the sources consulted, model preparation and generation in Blender. Create an object to begin.', phases: 'Generation stages', elapsed: 'Time since request', events: 'Activity log', attempt_one: 'Attempt {{count}}', attempt_other: 'Attempt {{count}}', details: 'View details', loading: 'Loading activity…', waiting: 'Waiting for the first recorded activity…', noHistory: 'This creation predates activity recording. Its detailed history is unavailable.', unavailable: 'We could not load activity. Reconnecting shortly.', reconnecting: 'Activity disconnected. Retrying…', observed: 'Actions and results recorded during generation.', follow: 'Follow latest',
    connection: { connecting: 'Connecting…', live: 'Live', polling: 'Checking for updates', offline: 'Disconnected', history: 'Saved history' },
    steps: { product: 'Product', model: 'Model', render: 'Render', validate: 'Validation', ready: 'Ready' },
    kinds: { queued: 'Queued', analysis: 'Product analysis', search: 'Search', source: 'Source consulted', reference: 'Visual reference', review: 'Visual review', revision: 'Model correction', plan: 'Object plan', question: 'Your answer is needed', answer: 'Answer received', modeling: 'Modelling', render: 'Render', validation: 'Validation', complete: 'Object saved', error: 'Error', cancelled: 'Cancelled', retry: 'New attempt' },
  },
  references: {
    attached: 'Reference photos attached.',
    title: 'Reference photos (optional)', help: 'Up to 4 PNG, JPEG or WebP photos, up to 5 MB each. Show the front, side and details you want to preserve.', tooMany: 'You can attach up to 4 photos per request.', invalid: 'Choose PNG, JPEG or WebP photos up to 5 MB each.', failed: 'We could not upload the photo. Please try again.', uploading: 'Uploading photos…', remove: 'Remove {{name}}', compare: 'Reference and result', original: 'Reference photo', generated: 'Generated render', photo_one: 'Photo {{count}}', photo_other: 'Photo {{count}}', none: 'There are no saved reference photos yet. Attach some below to guide the next version.', unavailable: 'We could not load the reference photos.', someUnavailable: 'Some reference photos are unavailable.', loading: 'Loading reference photos…',
  },
  revision: {
    eyebrow: 'Iterate on this object', title: 'Improve the resemblance', help: 'Describe what differs from the product. We will create a new version from this model, your feedback and the available photos.', feedback: 'What needs correcting?', placeholder: 'The back should be rounder; the seat is too high; the fabric texture is missing…', submit: 'Create improved version', preserved: 'Version {{count}} and its files are preserved. Photos you attach replace the references for the new version.', created: 'Correction received. Follow the new version in the activity panel.', version_one: 'Version {{count}}', version_other: 'Version {{count}}', versions_one: '{{count}} version', versions_other: '{{count}} versions', history: 'Version history', previous: 'View previous version', review: 'Automatic visual review', iterations_one: '{{count}} recorded iteration', iterations_other: '{{count}} recorded iterations', reviewLimit: 'Automatic review guides corrections; the result remains a draft for you to assess.', verdict: { accept: 'Visual comparison accepted', revise: 'Differences remain to be corrected', needs_input: 'More visual information needed' },
  },
  library: {
    title: 'Your library', count_one: '{{count}} object', count_other: '{{count}} objects', emptyTitle: 'The next object starts with a link', emptyDescription: 'Generated models, measurements and source files will be saved in your account’s private library.', select: 'Review {{label}}', draft: 'Visual draft', draftHelp: 'Review the shape and materials before use. Outer dimensions are validated when the model is generated.', dimensions: 'Width × height × depth', measurements: 'Measurement source', estimated: 'Estimated', 'user-supplied': 'Provided by you', 'manufacturer-specified': 'Manufacturer’s product page', source: 'View original product', evidence: 'Product information', warnings: 'Details to review', preview: 'Image', model: 'Explore in 3D', loading: 'Loading model…', noWebGL: 'The 3D view needs WebGL 2. You can review the image or download the model.', modelFailed: 'We could not open the 3D view. The image and downloads are still available.', drag: 'Drag to rotate · Scroll to zoom', downloads: 'Download files', glb: 'GLB model', blend: 'Blender source', manifest: 'Technical record', selected: 'Selected object',
  },
} as const
