import publicDemo from './public-assets.ts'

export default {
  publicDemo,
  eyebrow: 'Tu taller de objetos',
  title: 'De un producto a tu biblioteca',
  description: 'Pegá un enlace, completá los detalles y creá un objeto 3D con las medidas y referencias disponibles para tu proyecto.',
  connection: { generationDisabled: 'La generación está deshabilitada para esta cuenta. Podés consultar tu biblioteca y usarla en tus proyectos.', checking: 'Conectando al taller…', online: 'Taller conectado', offline: 'Taller desconectado', reconnect: 'Volver a conectar', offlineHelp: 'El servicio del taller no responde. Reintentá más tarde; si el problema sigue, contactá al administrador.', login: 'El servicio de IA no está disponible. Pedile al administrador que revise la configuración.', blender: 'El servicio de modelado 3D no está disponible. Contactá al administrador para que revise el taller.' },
  form: {
    title: 'Crear un objeto', subtitle: 'La página del producto es el punto de partida.', url: 'Enlace del producto', urlPlaceholder: 'https://www.ikea.com/…', invalidUrl: 'Usá un enlace público http o https, sin credenciales ni puertos especiales.', notes: 'Detalles y preferencias', notesPlaceholder: 'Color, material, variante del producto o detalles que querés conservar…', dimensions: 'Medidas conocidas (opcional)', dimensionHelp: 'Medidas exteriores en centímetros. Completá las tres o dejalas vacías para buscar las de la ficha.', width: 'Ancho', height: 'Alto', depth: 'Fondo', submit: 'Crear objeto 3D', sending: 'Enviando…', footnote: 'La generación usa OpenAI y consume créditos de tu cuenta. Los archivos se generan en el servidor y se guardan en tu biblioteca privada.', invalidDimensions: 'Completá ancho, alto y fondo con valores entre 5 y 2.000 cm.', created: 'Solicitud recibida. Seguí la generación en el panel de actividad.', requestFailed: 'No pudimos completar la solicitud. Volvé a intentarlo.',
  },
  jobs: {
    title: 'Actividad del taller', empty: 'Tus próximas creaciones aparecerán acá.', cancel: 'Cancelar', retry: 'Reintentar', answer: 'Completar información', answerLabel: 'Tu respuesta', answerPlaceholder: 'Aclaraciones, medidas o detalles del producto…', continue: 'Continuar generación', view: 'Ver objeto', queued: 'En cola', analyzing: 'Estudiando el producto', needs_input: 'Necesita tu respuesta', generating: 'Modelando en Blender', completed: 'Objeto generado', failed: 'No se pudo generar', cancelled: 'Cancelado', busy: 'Actualizando…', questions: 'Antes de continuar', untitled: 'Nuevo objeto',
  },
  activity: {
    title: 'Generación en vivo', history: 'Creación seleccionada', newObject: 'Nuevo objeto', view: 'Ver actividad', intro: 'Acá vas a seguir cada paso: las fuentes consultadas, el modelo preparado y la generación en Blender. Creá un objeto para empezar.', phases: 'Etapas de generación', elapsed: 'Tiempo desde la solicitud', events: 'Registro de actividad', attempt_one: 'Intento {{count}}', attempt_other: 'Intento {{count}}', details: 'Ver detalles', loading: 'Cargando la actividad…', waiting: 'Esperando la primera actividad registrada…', noHistory: 'Esta creación es anterior al registro de actividad. Su historial detallado no está disponible.', unavailable: 'No pudimos cargar la actividad. Vamos a volver a conectarnos.', reconnecting: 'Sin conexión con la actividad. Reintentando…', observed: 'Acciones y resultados registrados durante la generación.', follow: 'Seguir lo último',
    connection: { connecting: 'Conectando…', live: 'En vivo', polling: 'Actualizando periódicamente', offline: 'Sin conexión', history: 'Historial guardado' },
    steps: { product: 'Producto', model: 'Modelo', render: 'Render', validate: 'Validación', ready: 'Listo' },
    kinds: { queued: 'En cola', analysis: 'Análisis del producto', search: 'Búsqueda', source: 'Fuente consultada', reference: 'Referencia visual', review: 'Revisión visual', revision: 'Corrección del modelo', plan: 'Plan del objeto', question: 'Necesita tu respuesta', answer: 'Respuesta recibida', modeling: 'Modelado', render: 'Render', validation: 'Validación', complete: 'Objeto guardado', error: 'Error', cancelled: 'Cancelado', retry: 'Nuevo intento' },
  },
  references: {
    attached: 'Fotos de referencia adjuntas.',
    title: 'Fotos de referencia (opcional)', help: 'Hasta 4 fotos PNG, JPEG o WebP, de hasta 5 MB cada una. Mostrá el frente, el lateral y los detalles que querés conservar.', tooMany: 'Podés adjuntar hasta 4 fotos por solicitud.', invalid: 'Elegí fotos PNG, JPEG o WebP de hasta 5 MB cada una.', failed: 'No pudimos subir la foto. Volvé a intentarlo.', uploading: 'Subiendo fotos…', remove: 'Quitar {{name}}', compare: 'Referencia y resultado', original: 'Foto de referencia', generated: 'Render generado', photo_one: 'Foto {{count}}', photo_other: 'Foto {{count}}', none: 'Todavía no hay fotos guardadas para comparar. Adjuntalas abajo para orientar la próxima versión.', unavailable: 'No pudimos cargar las fotos de referencia.', someUnavailable: 'Algunas fotos de referencia no están disponibles.', loading: 'Cargando fotos de referencia…',
  },
  revision: {
    eyebrow: 'Iterar sobre este objeto', title: 'Mejorar el parecido', help: 'Contá qué no coincide con el producto. Vamos a generar una nueva versión a partir de este modelo, tus indicaciones y las fotos disponibles.', feedback: '¿Qué hay que corregir?', placeholder: 'El respaldo debería ser más redondeado; el asiento está demasiado alto; falta la textura de la tela…', submit: 'Crear versión mejorada', preserved: 'La versión {{count}} y sus archivos se conservan. Si adjuntás fotos, reemplazan las referencias de la nueva versión.', created: 'Corrección recibida. Podés seguir la nueva versión en el panel de actividad.', version_one: 'Versión {{count}}', version_other: 'Versión {{count}}', versions_one: '{{count}} versión', versions_other: '{{count}} versiones', history: 'Historial de versiones', previous: 'Ver versión anterior', review: 'Revisión visual automática', iterations_one: '{{count}} iteración registrada', iterations_other: '{{count}} iteraciones registradas', reviewLimit: 'La revisión automática orienta las correcciones; el resultado sigue siendo un borrador para que vos lo evalúes.', verdict: { accept: 'Comparación visual aceptada', revise: 'Quedan diferencias por corregir', needs_input: 'Falta información visual' },
  },
  library: {
    title: 'Tu biblioteca', count_one: '{{count}} objeto', count_other: '{{count}} objetos', emptyTitle: 'El próximo objeto empieza con un enlace', emptyDescription: 'Los modelos generados, sus medidas y archivos quedarán guardados en la biblioteca privada de tu cuenta.', select: 'Revisar {{label}}', draft: 'Borrador visual', draftHelp: 'Revisá la forma y los materiales antes de usarlo. Las medidas exteriores se validan al generar el modelo.', dimensions: 'Ancho × alto × fondo', measurements: 'Origen de las medidas', estimated: 'Estimadas', 'user-supplied': 'Aportadas por vos', 'manufacturer-specified': 'Ficha del fabricante', source: 'Ver producto original', evidence: 'Datos del producto', warnings: 'Detalles a revisar', preview: 'Imagen', model: 'Explorar en 3D', loading: 'Cargando modelo…', noWebGL: 'La vista 3D necesita WebGL 2. Podés revisar la imagen o descargar el modelo.', modelFailed: 'No pudimos abrir la vista 3D. La imagen y las descargas siguen disponibles.', drag: 'Arrastrá para girar · Deslizá para acercar', downloads: 'Descargar archivos', glb: 'Modelo GLB', blend: 'Fuente Blender', manifest: 'Ficha técnica', selected: 'Objeto seleccionado',
  },
} as const
