import publicDemo from './public-assets.ts'

export default {
  publicDemo,
  eyebrow: 'Votre atelier d’objets',
  title: 'Du produit à votre bibliothèque',
  description: 'Collez un lien, ajoutez les détails et créez un objet 3D à partir des dimensions et références disponibles pour votre projet.',
  connection: { generationDisabled: 'La génération est désactivée pour ce compte. Vous pouvez consulter votre bibliothèque et utiliser ses objets dans vos projets.', checking: 'Connexion à l’atelier…', online: 'Atelier connecté', offline: 'Atelier déconnecté', reconnect: 'Reconnecter', offlineHelp: 'Le service de l’atelier ne répond pas. Réessayez plus tard ; si le problème persiste, contactez l’administrateur.', login: 'Le service IA est indisponible. Demandez à l’administrateur de vérifier sa configuration.', blender: 'Le service de modélisation 3D est indisponible. Contactez l’administrateur pour vérifier l’atelier.' },
  form: {
    title: 'Créer un objet', subtitle: 'La fiche du produit est le point de départ.', url: 'Lien du produit', urlPlaceholder: 'https://www.ikea.com/…', invalidUrl: 'Utilisez un lien public http ou https sans identifiants ni port personnalisé.', notes: 'Détails et préférences', notesPlaceholder: 'Couleur, matériau, variante du produit ou détails à conserver…', dimensions: 'Dimensions connues (facultatif)', dimensionHelp: 'Dimensions extérieures en centimètres. Remplissez les trois ou laissez-les vides pour utiliser la fiche du produit.', width: 'Largeur', height: 'Hauteur', depth: 'Profondeur', submit: 'Créer l’objet 3D', sending: 'Envoi…', footnote: 'La génération utilise OpenAI et consomme les crédits de votre compte. Les fichiers sont générés sur le serveur et conservés dans votre bibliothèque privée.', invalidDimensions: 'Indiquez largeur, hauteur et profondeur entre 5 et 2 000 cm.', created: 'Demande reçue. Suivez la génération dans le panneau d’activité.', requestFailed: 'La demande n’a pas abouti. Veuillez réessayer.',
  },
  jobs: {
    title: 'Activité de l’atelier', empty: 'Vos prochaines créations apparaîtront ici.', cancel: 'Annuler', retry: 'Réessayer', answer: 'Compléter les informations', answerLabel: 'Votre réponse', answerPlaceholder: 'Précisions, dimensions ou détails du produit…', continue: 'Continuer la génération', view: 'Voir l’objet', queued: 'En attente', analyzing: 'Analyse du produit', needs_input: 'Votre réponse est attendue', generating: 'Modélisation dans Blender', completed: 'Objet généré', failed: 'Échec de la génération', cancelled: 'Annulé', busy: 'Mise à jour…', questions: 'Avant de continuer', untitled: 'Nouvel objet',
  },
  activity: {
    title: 'Génération en direct', history: 'Création sélectionnée', newObject: 'Nouvel objet', view: 'Voir l’activité', intro: 'Suivez chaque étape : les sources consultées, le modèle préparé et la génération dans Blender. Créez un objet pour commencer.', phases: 'Étapes de génération', elapsed: 'Temps depuis la demande', events: 'Journal d’activité', attempt_one: 'Tentative {{count}}', attempt_other: 'Tentative {{count}}', details: 'Voir les détails', loading: 'Chargement de l’activité…', waiting: 'En attente de la première activité enregistrée…', noHistory: 'Cette création précède l’enregistrement de l’activité. Son historique détaillé est indisponible.', unavailable: 'Impossible de charger l’activité. Reconnexion en cours.', reconnecting: 'Activité déconnectée. Nouvelle tentative…', observed: 'Actions et résultats enregistrés pendant la génération.', follow: 'Suivre la suite',
    connection: { connecting: 'Connexion…', live: 'En direct', polling: 'Vérification des mises à jour', offline: 'Déconnecté', history: 'Historique enregistré' },
    steps: { product: 'Produit', model: 'Modèle', render: 'Rendu', validate: 'Validation', ready: 'Prêt' },
    kinds: { queued: 'En attente', analysis: 'Analyse du produit', search: 'Recherche', source: 'Source consultée', reference: 'Référence visuelle', review: 'Évaluation visuelle', revision: 'Correction du modèle', plan: 'Plan de l’objet', question: 'Votre réponse est attendue', answer: 'Réponse reçue', modeling: 'Modélisation', render: 'Rendu', validation: 'Validation', complete: 'Objet enregistré', error: 'Erreur', cancelled: 'Annulé', retry: 'Nouvelle tentative' },
  },
  references: {
    attached: 'Photos de référence jointes.',
    title: 'Photos de référence (facultatif)', help: 'Jusqu’à 4 photos PNG, JPEG ou WebP, de 5 Mo maximum chacune. Montrez la face, le côté et les détails à préserver.', tooMany: 'Vous pouvez joindre jusqu’à 4 photos par demande.', invalid: 'Choisissez des photos PNG, JPEG ou WebP de 5 Mo maximum chacune.', failed: 'Impossible d’envoyer la photo. Veuillez réessayer.', uploading: 'Envoi des photos…', remove: 'Retirer {{name}}', compare: 'Référence et résultat', original: 'Photo de référence', generated: 'Rendu généré', photo_one: 'Photo {{count}}', photo_other: 'Photo {{count}}', none: 'Aucune photo de référence enregistrée. Ajoutez-en ci-dessous pour guider la prochaine version.', unavailable: 'Impossible de charger les photos de référence.', someUnavailable: 'Certaines photos de référence sont indisponibles.', loading: 'Chargement des photos de référence…',
  },
  revision: {
    eyebrow: 'Faire évoluer cet objet', title: 'Améliorer la ressemblance', help: 'Décrivez les différences avec le produit. Nous créerons une nouvelle version à partir de ce modèle, de vos remarques et des photos disponibles.', feedback: 'Que faut-il corriger ?', placeholder: 'Le dossier devrait être plus arrondi ; l’assise est trop haute ; la texture du tissu manque…', submit: 'Créer une version améliorée', preserved: 'La version {{count}} et ses fichiers sont conservés. Les photos jointes remplacent les références de la nouvelle version.', created: 'Correction reçue. Suivez la nouvelle version dans le panneau d’activité.', version_one: 'Version {{count}}', version_other: 'Version {{count}}', versions_one: '{{count}} version', versions_other: '{{count}} versions', history: 'Historique des versions', previous: 'Voir la version précédente', review: 'Évaluation visuelle automatique', iterations_one: '{{count}} itération enregistrée', iterations_other: '{{count}} itérations enregistrées', reviewLimit: 'L’évaluation automatique guide les corrections ; le résultat reste une ébauche à examiner.', verdict: { accept: 'Comparaison visuelle acceptée', revise: 'Des différences restent à corriger', needs_input: 'Informations visuelles manquantes' },
  },
  library: {
    title: 'Votre bibliothèque', count_one: '{{count}} objet', count_other: '{{count}} objets', emptyTitle: 'Le prochain objet commence par un lien', emptyDescription: 'Les modèles générés, leurs dimensions et leurs fichiers sources seront conservés dans la bibliothèque privée de votre compte.', select: 'Examiner {{label}}', draft: 'Ébauche visuelle', draftHelp: 'Vérifiez la forme et les matériaux avant utilisation. Les dimensions extérieures sont validées lors de la génération du modèle.', dimensions: 'Largeur × hauteur × profondeur', measurements: 'Origine des dimensions', estimated: 'Estimées', 'user-supplied': 'Fournies par vous', 'manufacturer-specified': 'Fiche du fabricant', source: 'Voir le produit d’origine', evidence: 'Informations du produit', warnings: 'Détails à vérifier', preview: 'Image', model: 'Explorer en 3D', loading: 'Chargement du modèle…', noWebGL: 'La vue 3D nécessite WebGL 2. Vous pouvez consulter l’image ou télécharger le modèle.', modelFailed: 'Impossible d’ouvrir la vue 3D. L’image et les téléchargements restent disponibles.', drag: 'Glisser pour tourner · Défiler pour zoomer', downloads: 'Télécharger les fichiers', glb: 'Modèle GLB', blend: 'Source Blender', manifest: 'Fiche technique', selected: 'Objet sélectionné',
  },
} as const
