import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { goTo, mutate, request, type AccountUser } from './api'
import { getAccountCopy } from './account-copy'
import type { BillingSummary, CreditSummary } from './account-api'
import type { PrivateCopy } from './copy'
import { button, Field, Feedback, input, muted, panel, primary } from './ui'

type Invite = { id: string; email?: string; tier: 'standard' | 'premium'; createdAt: string; expiresAt: string; usedAt?: string | null; revokedAt?: string | null; maxUses?: number; uses?: number }

export function People({ c, user, language }: { c: PrivateCopy; user: AccountUser; language: string }) {
  const a = getAccountCopy(language)
  const admin = user.role === 'admin'
  const [users, setUsers] = useState<AccountUser[]>([])
  const [trial, setTrial] = useState<CreditSummary | null>(null)
  const [invitations, setInvitations] = useState<Invite[]>([])
  const [links, setLinks] = useState<Invite[]>([])
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [invitation, setInvitation] = useState<{ url: string; expiresAt: string; email?: string } | null>(null)
  const [copied, setCopied] = useState(false)
  const creditRequests = useRef(new Map<string, string>())
  const load = useCallback(async (signal?: AbortSignal) => {
    const [personal, shared, accounts, allowance] = await Promise.all([request<{ invitations: Invite[] }>('/api/account/invitations', { signal }), request<{ links: Invite[] }>('/api/account/invitation-links', { signal }), admin ? request<{ users: AccountUser[] }>('/api/account/users', { signal }) : Promise.resolve({ users: [] }), request<CreditSummary>('/api/credits', { signal })])
    setInvitations(personal.invitations); setLinks(shared.links); setUsers(accounts.users); setTrial(allowance); setLoading(false)
  }, [admin])
  useEffect(() => { const abort = new AbortController(); void load(abort.signal).catch(() => { if (!abort.signal.aborted) { setError(c.unavailable); setLoading(false) } }); return () => abort.abort() }, [load, c.unavailable])
  async function perform(operation: () => Promise<void>, success = '') {
    if (busy) return; setBusy(true); setError(''); setNotice('')
    try { await operation(); setNotice(success); window.dispatchEvent(new Event('t3:credits-changed')); try { await load() } catch { setError(c.unavailable) } } catch { setError(c.genericError) } finally { setBusy(false) }
  }
  async function invite(event: FormEvent<HTMLFormElement>, shareable: boolean) {
    event.preventDefault(); const form = event.currentTarget; const fields = new FormData(form)
    await perform(async () => {
      const tier = admin ? String(fields.get('tier')) : 'standard'
      const email = String(fields.get('email') ?? '').trim()
      const data = await mutate<{ invitation?: Invite; link?: Invite; token: string }>(`/api/account/${shareable ? 'invitation-links' : 'invitations'}`, shareable ? { tier, maxUses: Number(fields.get('maxUses')), expiresInDays: Number(fields.get('days')) } : { email, tier })
      const created = data.invitation ?? data.link
      if (!created) throw new Error('Invalid invitation response')
      setInvitation({ url: `${window.location.origin}/invite#token=${encodeURIComponent(data.token)}`, expiresAt: created.expiresAt, ...(shareable ? {} : { email }) }); setCopied(false); form.reset()
    })
  }
  const tierPicker = admin && <Field label={a.invitationTier}><select className={input} name="tier" disabled={busy}><option value="standard">{a.standard}</option><option value="premium">{a.premium}</option></select></Field>
  function state(item: Invite) { return item.revokedAt ? a.revoked : item.usedAt ? a.used : Date.parse(item.expiresAt) <= Date.now() ? a.expired : item.maxUses && (item.uses ?? 0) >= item.maxUses ? a.allUsed : c.active }
  return <>
    <p className={`${muted} tw:mt-0 tw:text-xs tw:font-semibold tw:uppercase tw:tracking-widest`}>{admin ? c.users : a.invitations}</p><h1 className="tw:mt-0! tw:text-3xl! tw:font-medium!">{c.peopleTitle}</h1><p className={`${muted} tw:text-sm tw:leading-6`}>{c.peopleIntro} {trial ? a.inviteTrial.replace('{days}', String(trial.trialDays)).replace('{credits}', String(trial.trialCredits)) : ''}</p>
    <div className="tw:my-6 tw:grid tw:gap-5 tw:md:grid-cols-2">
      <form className={`${panel} tw:flex tw:flex-col tw:gap-4 tw:p-5`} onSubmit={event => { void invite(event, false) }}><h2 className="tw:m-0 tw:text-lg tw:font-medium">{a.personal}</h2><Field label={c.inviteEmail}><input className={input} type="email" name="email" required maxLength={254} disabled={busy} /></Field>{tierPicker}<button className={primary} disabled={busy}>{busy ? c.pending : c.invite}</button></form>
      <form className={`${panel} tw:flex tw:flex-col tw:gap-4 tw:p-5`} onSubmit={event => { void invite(event, true) }}><h2 className="tw:m-0 tw:text-lg tw:font-medium">{a.shareable}</h2><p className={`${muted} tw:m-0 tw:text-xs tw:leading-6`}>{a.linkHelp}</p><div className="tw:grid tw:grid-cols-2 tw:gap-3"><Field label={a.maxUses}><input className={input} type="number" name="maxUses" min={1} max={admin ? 100 : 10} defaultValue={5} required disabled={busy} /></Field><Field label={a.linkDays}><input className={input} type="number" name="days" min={1} max={30} defaultValue={7} required disabled={busy} /></Field></div>{tierPicker}<button className={primary} disabled={busy}>{busy ? c.pending : a.createLink}</button></form>
    </div>
    <Feedback message={error} error /><Feedback message={notice} />
    {invitation && <section className={`${panel} tw:my-5 tw:bg-[var(--settings-accent-soft)] tw:p-5`}><h2 className="tw:mt-0 tw:text-lg tw:font-medium">{c.invitationReady}{invitation.email ? `: ${invitation.email}` : ''}</h2><p className={`${muted} tw:text-xs tw:leading-6`}>{a.expires}: {new Date(invitation.expiresAt).toLocaleString(language)}. {invitation.email ? c.invitationHelp.split('. ')[0] : a.linkHelp}</p><Field label={invitation.email ? c.invitationLink : a.linkLabel}><input className={input} readOnly value={invitation.url} onFocus={event => event.currentTarget.select()} /></Field><button className={`${button} tw:mt-3`} onClick={() => { void navigator.clipboard.writeText(invitation.url).then(() => setCopied(true)).catch(() => setNotice(c.copyFailed)) }}>{copied ? c.copied : c.copy}</button></section>}
    <section className="tw:my-8"><h2 className="tw:text-xl tw:font-medium">{a.activeInvites}</h2>{loading ? <p role="status" className={muted}>{c.loading}</p> : !invitations.length && !links.length ? <p className={muted}>{a.noInvites}</p> : <div className="tw:flex tw:flex-col tw:gap-3">{[...invitations, ...links].map(item => <article key={item.id} className={`${panel} tw:flex tw:flex-wrap tw:items-center tw:justify-between tw:gap-4 tw:p-4`}><div className="tw:min-w-0"><h3 className="tw:m-0 tw:break-all tw:text-sm tw:font-medium">{item.email ?? a.shareable}</h3><p className={`${muted} tw:mb-0 tw:text-xs tw:leading-6`}>{item.tier === 'premium' ? a.premium : a.standard} · {state(item)} · {a.expires}: {new Date(item.expiresAt).toLocaleDateString(language)}{item.maxUses ? ` · ${a.uses}: ${item.uses ?? 0}/${item.maxUses}` : ''}</p></div><button className={button} disabled={busy || state(item) !== c.active} onClick={() => { void perform(async () => { await mutate(`/api/account/${item.email ? 'invitations' : 'invitation-links'}/${item.id}/revoke`, {}) }) }}>{a.revokeLink}</button></article>)}</div>}</section>
    {admin && <section><h2 className="tw:text-xl tw:font-medium">{c.users}</h2><div className="tw:flex tw:flex-col tw:gap-4">{users.map(person => <article key={person.id} className={`${panel} tw:p-5`}><div className="tw:flex tw:flex-wrap tw:items-start tw:justify-between tw:gap-4"><div className="tw:min-w-0"><h3 className="tw:m-0 tw:text-base tw:font-medium">{person.name} {person.id === user.id && <span className={`${muted} tw:text-xs`}>· {c.ownAccount}</span>}</h3><p className={`${muted} tw:my-2 tw:break-all tw:text-xs`}>{person.email}</p><p className="tw:m-0 tw:text-xs">{person.role === 'admin' ? c.administrator : c.member} · {person.tier === 'premium' ? a.premium : a.standard} · {person.suspended ? c.suspended : c.active}</p></div><div className="tw:flex tw:flex-wrap tw:gap-2">{person.role !== 'admin' && <button className={button} disabled={busy} onClick={() => { void perform(async () => { await mutate(`/api/account/users/${person.id}/tier`, { tier: person.tier === 'premium' ? 'standard' : 'premium' }) }, a.saved) }}>{person.tier === 'premium' ? a.removePremium : a.grantPremium}</button>}{person.id !== user.id && <><button className={button} disabled={busy} onClick={() => { void perform(async () => { await mutate(`/api/account/users/${person.id}/revoke-sessions`, {}) }, c.sessionsRevoked) }}>{c.revoke}</button><button className={button} disabled={busy} onClick={() => { void perform(async () => { await mutate(`/api/account/users/${person.id}/suspend`, { suspended: !person.suspended }) }) }}>{person.suspended ? c.reactivate : c.suspend}</button></>}</div></div><details className="tw:mt-4"><summary className={`${muted} tw:cursor-pointer tw:text-sm`}>{a.grant}</summary><p className={`${muted} tw:text-xs tw:leading-6`}>{a.grantHelp}</p><form className="tw:flex tw:flex-wrap tw:items-end tw:gap-3" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const amount = Number(data.get('amount')); const reason = String(data.get('reason')).trim(); const key = JSON.stringify([person.id, amount, reason]); const requestId = creditRequests.current.get(key) ?? crypto.randomUUID(); creditRequests.current.set(key, requestId); void perform(async () => { await mutate(`/api/account/users/${person.id}/credits`, { amount, reason, requestId }); creditRequests.current.delete(key); form.reset() }, a.grantSaved) }}><Field label={a.amount}><input className={`${input} tw:max-w-32`} type="number" name="amount" min={1} max={100000} required disabled={busy} /></Field><div className="tw:min-w-48 tw:flex-1"><Field label={a.grantReason}><input className={input} name="reason" maxLength={200} required disabled={busy} /></Field></div><button className={button} disabled={busy}>{a.grant}</button></form></details></article>)}</div></section>}
  </>
}

export function CreditBadge({ language }: { language: string }) {
  const [credits, setCredits] = useState<CreditSummary | null>(null)
  const a = getAccountCopy(language)
  useEffect(() => {
    const abort = new AbortController()
    const load = () => { if (!document.hidden) void request<CreditSummary>('/api/credits', { signal: abort.signal }).then(data => { if (typeof data.balance === 'number') setCredits(data) }).catch(() => undefined) }
    load(); const interval = setInterval(load, 30_000); window.addEventListener('t3:credits-changed', load)
    return () => { abort.abort(); clearInterval(interval); window.removeEventListener('t3:credits-changed', load) }
  }, [])
  return <a href="/app/credits" onClick={event => { if (event.button === 0 && !event.metaKey && !event.ctrlKey && !event.shiftKey && !event.altKey) { event.preventDefault(); goTo('/app/credits') } }} className="tw:mb-5 tw:block tw:rounded-lg tw:bg-[var(--settings-accent-soft)] tw:px-3 tw:py-3 tw:text-sm tw:text-[color:var(--settings-accent)] tw:no-underline">{credits ? `${credits.balance.toLocaleString(language)} ${a.creditUnit}` : a.credits}</a>
}

export function CreditWallet({ language, c }: { language: string; c: PrivateCopy }) {
  const a = getAccountCopy(language)
  const [credits, setCredits] = useState<CreditSummary | null>(null)
  const [billing, setBilling] = useState<BillingSummary | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [checkout, setCheckout] = useState<{ orderId: string; checkoutUrl: string | null; mode: BillingSummary['mode'] } | null>(null)
  const load = useCallback(async (signal?: AbortSignal) => {
    const [creditData, billingData] = await Promise.all([request<CreditSummary>('/api/credits', { signal }), request<BillingSummary>('/api/billing', { signal })])
    setCredits(creditData); setBilling(billingData)
  }, [])
  useEffect(() => { const abort = new AbortController(); void load(abort.signal).catch(() => { if (!abort.signal.aborted) setError(c.unavailable) }); return () => abort.abort() }, [load, c.unavailable])
  async function perform(operation: () => Promise<void>, message = '') { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await operation(); await load(); window.dispatchEvent(new Event('t3:credits-changed')); setNotice(message) } catch { setError(c.genericError) } finally { setBusy(false) } }
  const date = (value: string | null) => value ? new Date(value).toLocaleString(language) : a.never
  const price = (amount: number) => new Intl.NumberFormat(language, { style: 'currency', currency: 'ARS', currencyDisplay: 'code' }).format(amount)
  const mock = language.startsWith('es') ? { label: 'Simulación local: no se realizan cobros reales.', approve: 'Simular pago de prueba', done: 'Pago de prueba simulado. No se cobró dinero.' } : language.startsWith('fr') ? { label: 'Simulation locale : aucun paiement réel.', approve: 'Simuler un paiement test', done: 'Paiement test simulé. Aucun montant débité.' } : { label: 'Local simulation: no real payments are collected.', approve: 'Simulate test payment', done: 'Test payment simulated. No money was collected.' }
  const statusLabel = (status: string) => {
    const values = language.startsWith('es') ? { pending: 'Pendiente', approved: 'Aprobado', authorized: 'Autorizada', active: 'Activa', canceled: 'Cancelada', cancelled: 'Cancelada', rejected: 'Rechazado', refunded: 'Reembolsado', charged_back: 'Contracargo' } : language.startsWith('fr') ? { pending: 'En attente', approved: 'Approuvé', authorized: 'Autorisé', active: 'Actif', canceled: 'Annulé', cancelled: 'Annulé', rejected: 'Refusé', refunded: 'Remboursé', charged_back: 'Rétrofacturé' } : { pending: 'Pending', approved: 'Approved', authorized: 'Authorized', active: 'Active', canceled: 'Canceled', cancelled: 'Canceled', rejected: 'Rejected', refunded: 'Refunded', charged_back: 'Charged back' }
    return values[status as keyof typeof values] ?? status
  }
  return <>
    <div className="tw:mb-6 tw:flex tw:flex-wrap tw:items-start tw:justify-between tw:gap-4"><div><h1 className="tw:mt-0! tw:text-3xl! tw:font-medium!">{a.credits}</h1><p className={`${muted} tw:max-w-2xl tw:text-sm tw:leading-6`}>{a.walletIntro}</p></div><button className={button} disabled={busy} onClick={() => { void perform(async () => { await mutate('/api/billing/refresh', {}) }) }}>{busy ? c.pending : a.refresh}</button></div>
    <Feedback message={error} error /><Feedback message={notice} />
    {!credits || !billing ? <p role="status" className={muted}>{error ? a.creditUnavailable : c.loading}</p> : <>
      <div className="tw:grid tw:gap-5 tw:md:grid-cols-3"><section className={`${panel} tw:p-5`}><h2 className={`${muted} tw:m-0 tw:text-sm tw:font-normal`}>{a.balance}</h2><p className="tw:my-3 tw:text-4xl tw:font-medium" data-testid="credit-balance">{credits.balance.toLocaleString(language)}</p><p className={`${muted} tw:mb-0 tw:text-xs`}>{a.reserved}: {credits.reserved.toLocaleString(language)}</p></section><section className={`${panel} tw:p-5`}><h2 className="tw:mt-0 tw:text-base tw:font-medium">{credits.tier === 'premium' ? a.premium : a.standard}</h2><p className={`${muted} tw:text-xs tw:leading-6`}>{credits.tier === 'premium' ? a.premiumHelp : a.standardHelp}</p>{credits.tier === 'premium' && <p className="tw:text-sm">{a.allowance}: {credits.premiumMonthlyCredits.toLocaleString(language)}</p>}<p className="tw:mb-0 tw:text-xs tw:leading-6">{credits.tier === 'premium' ? `${a.nextAllowance}: ${date(credits.premiumPeriodEndsAt)}` : `${a.trialEnds}: ${date(credits.trialEndsAt)}`}</p>{credits.tier === 'standard' && !credits.trialActive && <p className={`${muted} tw:text-xs tw:leading-6`}>{a.trialEnded}</p>}</section><section className={`${panel} tw:p-5`}><h2 className="tw:mt-0 tw:text-base tw:font-medium">{a.cost}</h2><p className="tw:text-sm">{a.createCost}: {credits.costs.asset} {a.creditUnit}</p><p className="tw:text-sm">{a.revisionCost}: {credits.costs.revision} {a.creditUnit}</p><p className={`${muted} tw:mb-0 tw:text-xs tw:leading-6`}>{a.jobHold}</p></section></div>
      <p className={`${muted} tw:my-6 tw:text-sm tw:leading-6`}>{a.free}</p>
      <section className="tw:my-8"><h2 className="tw:text-xl tw:font-medium">{a.plans}</h2><p role="status" className={`${panel} tw:p-4 tw:text-sm tw:leading-6`}>{billing.mode === 'disabled' ? a.billingDisabled : billing.mode === 'mock' ? mock.label : a.billingSandbox}</p><div className="tw:grid tw:gap-4 tw:md:grid-cols-3">{billing.products.map(product => <article key={product.id} className={`${panel} tw:flex tw:flex-col tw:p-5`}><h3 className="tw:m-0 tw:text-lg tw:font-medium">{product.credits.toLocaleString(language)} {a.creditUnit}{product.kind === 'subscription' ? ` ${a.monthly}` : ''}</h3><p className="tw:my-4 tw:text-xl">{price(product.amount)}{product.kind === 'subscription' ? ` ${a.monthly}` : ''}</p><p className={`${muted} tw:mb-5 tw:mt-0 tw:text-xs tw:leading-6`}>{product.kind === 'subscription' ? a.monthlyExpiry : a.packExpiry}</p><button className={`${primary} tw:mt-auto`} disabled={busy || billing.mode === 'disabled' || (product.kind === 'subscription' && !!billing.subscription && !['canceled', 'cancelled'].includes(billing.subscription.status))} onClick={() => { void perform(async () => { const result = await mutate<{ orderId: string; checkoutUrl: string | null; mode: BillingSummary['mode'] }>('/api/billing/checkout', { product: product.id }); setCheckout(result) }, a.checkoutPending) }}>{product.kind === 'subscription' ? a.subscribe : a.buy}</button></article>)}</div>{checkout && <div className={`${panel} tw:mt-4 tw:p-4`}>{checkout.checkoutUrl && <a className={primary} href={checkout.checkoutUrl} target="_blank" rel="noreferrer">{a.openCheckout} ↗</a>}{checkout.mode === 'mock' && <button className={button} disabled={busy} onClick={() => { void perform(async () => { await mutate(`/api/billing/mock/${checkout.orderId}/approve`, {}); setCheckout(null) }, mock.done) }}>{mock.approve}</button>}</div>}</section>
      {billing.subscription && <section className={`${panel} tw:my-6 tw:p-5`}><h2 className="tw:mt-0 tw:text-lg tw:font-medium">{a.subscription}</h2><p className="tw:text-sm">{statusLabel(billing.subscription.status)} · {a.expires}: {billing.subscription.periodEndsAt ? date(billing.subscription.periodEndsAt) : c.pending}</p>{!['canceled', 'cancelled'].includes(billing.subscription.status) && <button className={button} disabled={busy} onClick={() => { if (window.confirm(a.cancelConfirm)) void perform(async () => { await mutate('/api/billing/cancel', {}) }, a.subscriptionCanceled) }}>{a.cancelSubscription}</button>}</section>}
      <section className="tw:my-8"><h2 className="tw:text-xl tw:font-medium">{a.grants}</h2><div className="tw:flex tw:flex-col tw:gap-3">{credits.grants.length ? credits.grants.map(grant => <div key={grant.id} className={`${panel} tw:flex tw:flex-wrap tw:items-center tw:justify-between tw:gap-3 tw:p-4`}><div><p className="tw:my-0 tw:text-sm">{grant.reason}</p><p className={`${muted} tw:mb-0 tw:text-xs`}>{a.expires}: {date(grant.expiresAt)}{grant.revokedAt ? ` · ${a.revoked}` : ''}</p></div><p className="tw:my-0 tw:text-sm">{a.remaining}: {grant.remaining}/{grant.amount}</p></div>) : <p className={muted}>{a.emptyHistory}</p>}</div></section>
      <section className="tw:my-8"><h2 className="tw:text-xl tw:font-medium">{a.history}</h2>{credits.transactions.length ? <div className={`${panel} tw:overflow-x-auto`}><table className="tw:w-full tw:border-collapse tw:text-left tw:text-sm"><thead><tr>{[a.date, a.reason, a.amount].map(label => <th key={label} scope="col" className="tw:p-4 tw:font-medium">{label}</th>)}</tr></thead><tbody>{credits.transactions.map(transaction => <tr key={transaction.id} className="tw:border-0 tw:border-t tw:border-solid tw:border-[var(--settings-border)]"><td className={`${muted} tw:p-4 tw:text-xs`}>{date(transaction.createdAt)}</td><td className="tw:p-4">{transaction.reason}</td><td className="tw:p-4">{transaction.amount > 0 ? '+' : ''}{transaction.amount.toLocaleString(language)}</td></tr>)}</tbody></table></div> : <p className={muted}>{a.emptyHistory}</p>}</section>
      <section className="tw:my-8"><h2 className="tw:text-xl tw:font-medium">{a.payments}</h2>{billing.orders.length ? <div className="tw:flex tw:flex-col tw:gap-3">{billing.orders.map(order => <div key={order.id} className={`${panel} tw:flex tw:flex-wrap tw:items-center tw:justify-between tw:gap-3 tw:p-4`}><div><p className="tw:m-0 tw:text-sm">{order.credits} {a.creditUnit} · {price(order.amount)}</p><p className={`${muted} tw:mb-0 tw:text-xs`}>{date(order.createdAt)} · {statusLabel(order.status)}</p></div>{order.checkoutUrl && !['approved', 'canceled', 'cancelled', 'refunded', 'charged_back'].includes(order.status) && <a className={button} href={order.checkoutUrl} target="_blank" rel="noreferrer">{a.openCheckout} ↗</a>}</div>)}</div> : <p className={muted}>{a.noPayments}</p>}</section>
    </>}
  </>
}
