const en = {
  credits: 'Credits & plan', invitations: 'Invitations', premium: 'Gifted premium', standard: 'Standard account', free: 'Create projects from the demo, edit and share them for free. Credits are used only for AI generation.',
  balance: 'Available credits', reserved: 'Reserved for running jobs', trialEnds: 'Trial ends', trialEnded: 'Your trial has ended. Your projects are still available.', allowance: 'Monthly allowance', nextAllowance: 'Next allowance', expires: 'Expires', never: 'No expiry', history: 'Credit activity', grants: 'Credit grants', emptyHistory: 'No activity yet.', amount: 'Credits', reason: 'Reason', date: 'Date', remaining: 'Remaining',
  walletIntro: 'Your balance funds AI assets and models. Review the cost before starting each generation.', premiumHelp: 'Gifted premium includes a monthly credit allowance and permission to invite standard accounts. It does not grant administration rights.', standardHelp: 'Standard accounts can use trial, subscription and purchased credits. A paid subscription does not grant invitation rights.',
  personal: 'Personal invitation', shareable: 'Shareable invitation', invitationTier: 'Access for this invitation', maxUses: 'Maximum accounts', linkDays: 'Link valid for (days)', createLink: 'Create shareable link', linkLabel: 'Shareable invitation link', linkHelp: 'Anyone with this link can create an account until it expires or reaches its limit. The trial starts when each person accepts.', inviteTrial: 'Standard invitations include a {days}-day trial and {credits} credits. The trial begins when the account is created.', invitePremium: 'Gifted premium receives a monthly allowance and may invite other people.', activeInvites: 'Invitations you can manage', revokeLink: 'Revoke invitation', revoked: 'Revoked', used: 'Accepted', uses: 'Accounts created', noInvites: 'No invitations yet.', expired: 'Expired', allUsed: 'Limit reached', saved: 'Account updated.',
  grantPremium: 'Give premium access', removePremium: 'Use standard access', grant: 'Grant credits', grantReason: 'Reason for this grant', grantHelp: 'Add credits to this account. This is recorded in the credit history.', grantSaved: 'Credits granted.',
  monthlyExpiry: 'Monthly credits expire at the end of each paid period.', packExpiry: 'Credit packs have no expiry.', plans: 'Plans & top-ups', billingDisabled: 'Payments are in development. Checkout is unavailable and no money is collected.', billingSandbox: 'Mercado Pago sandbox: use test payment details only. These purchases are for development.', subscribe: 'Choose subscription', buy: 'Buy credit pack', monthly: 'per month', checkoutPending: 'Checkout created. Credits are added only after the payment is verified.', checkoutFailed: 'We could not create checkout. Try again later.', openCheckout: 'Open Mercado Pago sandbox', subscription: 'Subscription', cancelSubscription: 'Cancel subscription', cancelConfirm: 'Cancel this subscription? Existing credit grants keep their original expiry.', subscriptionCanceled: 'Subscription canceled.', payments: 'Payment history', noPayments: 'No payments yet.', refresh: 'Refresh balance',
  trialWelcome: 'Your trial starts today when you create your account.', cost: 'Generation cost', createCost: 'New asset', revisionCost: 'Revision', creditUnit: 'credits', confirmGeneration: 'Start this generation for {cost} credits? Credits are reserved now; unexpired credits are returned if the job fails or is canceled.', insufficient: 'You do not have enough credits for this generation. Open Credits & plan to see your options.', creditUnavailable: 'We could not load your credit balance. Try again before starting a generation.', retryCost: 'A retry reserves the generation cost again.', jobHold: 'Running jobs reserve credits. Failed or canceled jobs release the reservation.',
} as const
export type AccountCopy = { [K in keyof typeof en]: string }
const es: AccountCopy = {
  credits: 'Créditos y plan', invitations: 'Invitaciones', premium: 'Premium de regalo', standard: 'Cuenta estándar', free: 'Crear proyectos desde la demo, editarlos y compartirlos es gratis. Los créditos se usan solo para generar con IA.',
  balance: 'Créditos disponibles', reserved: 'Reservados para trabajos en curso', trialEnds: 'Fin de la prueba', trialEnded: 'Tu prueba terminó. Tus proyectos siguen disponibles.', allowance: 'Créditos mensuales', nextAllowance: 'Próxima asignación', expires: 'Vence', never: 'Sin vencimiento', history: 'Movimientos de créditos', grants: 'Asignaciones de créditos', emptyHistory: 'Todavía no hay movimientos.', amount: 'Créditos', reason: 'Motivo', date: 'Fecha', remaining: 'Restantes',
  walletIntro: 'Usá tu saldo para generar assets y modelos con IA. Revisá el costo antes de iniciar cada generación.', premiumHelp: 'Premium de regalo incluye créditos mensuales y permiso para invitar cuentas estándar. No da permisos de administración.', standardHelp: 'Las cuentas estándar pueden usar créditos de prueba, suscripción y recargas. Una suscripción paga no habilita invitaciones.',
  personal: 'Invitación personal', shareable: 'Invitación compartible', invitationTier: 'Acceso de esta invitación', maxUses: 'Máximo de cuentas', linkDays: 'Vigencia del enlace (días)', createLink: 'Crear enlace compartible', linkLabel: 'Enlace compartible de invitación', linkHelp: 'Cualquiera con este enlace puede crear una cuenta hasta que venza o alcance el límite. La prueba empieza cuando cada persona lo acepta.', inviteTrial: 'Las invitaciones estándar incluyen {days} días de prueba y {credits} créditos iniciales. La prueba empieza al crear la cuenta.', invitePremium: 'Premium de regalo recibe créditos mensuales y puede invitar a otras personas.', activeInvites: 'Invitaciones que podés gestionar', revokeLink: 'Revocar invitación', revoked: 'Revocada', used: 'Aceptada', uses: 'Cuentas creadas', noInvites: 'Todavía no hay invitaciones.', expired: 'Vencida', allUsed: 'Límite alcanzado', saved: 'Cuenta actualizada.',
  grantPremium: 'Dar acceso premium', removePremium: 'Pasar a cuenta estándar', grant: 'Otorgar créditos', grantReason: 'Motivo de la asignación', grantHelp: 'Sumá créditos a esta cuenta. Quedará registrado en el historial.', grantSaved: 'Créditos otorgados.',
  monthlyExpiry: 'Los créditos mensuales vencen al finalizar cada período pagado.', packExpiry: 'Los paquetes de créditos no tienen vencimiento.', plans: 'Planes y recargas', billingDisabled: 'Los pagos están en desarrollo. El checkout no está disponible y no se cobra dinero.', billingSandbox: 'Sandbox de Mercado Pago: usá solo datos de pago de prueba. Estas compras son para desarrollo.', subscribe: 'Elegir suscripción', buy: 'Comprar paquete', monthly: 'por mes', checkoutPending: 'Checkout creado. Los créditos se agregan solo cuando se verifica el pago.', checkoutFailed: 'No pudimos crear el checkout. Intentá de nuevo más tarde.', openCheckout: 'Abrir sandbox de Mercado Pago', subscription: 'Suscripción', cancelSubscription: 'Cancelar suscripción', cancelConfirm: '¿Cancelar esta suscripción? Los créditos existentes conservan su vencimiento original.', subscriptionCanceled: 'Suscripción cancelada.', payments: 'Historial de pagos', noPayments: 'Todavía no hay pagos.', refresh: 'Actualizar saldo',
  trialWelcome: 'Tu prueba empieza cuando creás tu cuenta.', cost: 'Costo de generación', createCost: 'Nuevo asset', revisionCost: 'Revisión', creditUnit: 'créditos', confirmGeneration: '¿Iniciar esta generación por {cost} créditos? Se reservan ahora; si el trabajo falla o se cancela, se devuelven los créditos que sigan vigentes.', insufficient: 'No tenés créditos suficientes para esta generación. Abrí Créditos y plan para ver tus opciones.', creditUnavailable: 'No pudimos cargar tu saldo de créditos. Reintentá antes de iniciar una generación.', retryCost: 'Un reintento vuelve a reservar el costo de generación.', jobHold: 'Los trabajos en curso reservan créditos. Si fallan o se cancelan, se libera la reserva.',
}
const fr: AccountCopy = {
  credits: 'Crédits et offre', invitations: 'Invitations', premium: 'Premium offert', standard: 'Compte standard', free: 'Créer des projets depuis la démo, les modifier et les partager est gratuit. Les crédits servent uniquement à la génération par IA.',
  balance: 'Crédits disponibles', reserved: 'Réservés pour les tâches en cours', trialEnds: 'Fin de l’essai', trialEnded: 'Votre essai est terminé. Vos projets restent disponibles.', allowance: 'Crédits mensuels', nextAllowance: 'Prochaine attribution', expires: 'Expire le', never: 'Sans expiration', history: 'Historique des crédits', grants: 'Attributions de crédits', emptyHistory: 'Aucune activité pour le moment.', amount: 'Crédits', reason: 'Motif', date: 'Date', remaining: 'Restants',
  walletIntro: 'Votre solde finance les assets et modèles IA. Vérifiez le coût avant chaque génération.', premiumHelp: 'Premium offert inclut des crédits mensuels et le droit d’inviter des comptes standard. Il ne donne pas de droits d’administration.', standardHelp: 'Les comptes standard utilisent les crédits d’essai, d’abonnement et les recharges. Un abonnement payant ne donne pas le droit d’inviter.',
  personal: 'Invitation personnelle', shareable: 'Invitation partageable', invitationTier: 'Accès de cette invitation', maxUses: 'Nombre maximal de comptes', linkDays: 'Validité du lien (jours)', createLink: 'Créer un lien partageable', linkLabel: 'Lien d’invitation partageable', linkHelp: 'Toute personne ayant ce lien peut créer un compte jusqu’à son expiration ou sa limite. L’essai commence à chaque acceptation.', inviteTrial: 'Les invitations standard comprennent {days} jours d’essai et {credits} crédits. L’essai commence à la création du compte.', invitePremium: 'Premium offert reçoit des crédits mensuels et peut inviter d’autres personnes.', activeInvites: 'Invitations à gérer', revokeLink: 'Révoquer l’invitation', revoked: 'Révoquée', used: 'Acceptée', uses: 'Comptes créés', noInvites: 'Aucune invitation pour le moment.', expired: 'Expirée', allUsed: 'Limite atteinte', saved: 'Compte mis à jour.',
  grantPremium: 'Offrir un accès premium', removePremium: 'Passer au compte standard', grant: 'Attribuer des crédits', grantReason: 'Motif de l’attribution', grantHelp: 'Ajoutez des crédits à ce compte. Cette action est enregistrée dans l’historique.', grantSaved: 'Crédits attribués.',
  monthlyExpiry: 'Les crédits mensuels expirent à la fin de chaque période payée.', packExpiry: 'Les packs de crédits n’expirent pas.', plans: 'Offres et recharges', billingDisabled: 'Les paiements sont en développement. Le paiement est indisponible et aucun montant n’est débité.', billingSandbox: 'Sandbox Mercado Pago : utilisez uniquement des données de test. Ces achats servent au développement.', subscribe: 'Choisir l’abonnement', buy: 'Acheter des crédits', monthly: 'par mois', checkoutPending: 'Paiement créé. Les crédits seront ajoutés après vérification du paiement.', checkoutFailed: 'Impossible de créer le paiement. Réessayez plus tard.', openCheckout: 'Ouvrir la sandbox Mercado Pago', subscription: 'Abonnement', cancelSubscription: 'Annuler l’abonnement', cancelConfirm: 'Annuler cet abonnement ? Les crédits existants conservent leur date d’expiration.', subscriptionCanceled: 'Abonnement annulé.', payments: 'Historique des paiements', noPayments: 'Aucun paiement pour le moment.', refresh: 'Actualiser le solde',
  trialWelcome: 'Votre essai commence à la création de votre compte.', cost: 'Coût de génération', createCost: 'Nouvel asset', revisionCost: 'Révision', creditUnit: 'crédits', confirmGeneration: 'Lancer cette génération pour {cost} crédits ? Les crédits sont réservés maintenant ; les crédits non expirés sont rendus en cas d’échec ou d’annulation.', insufficient: 'Votre solde est insuffisant. Ouvrez Crédits et offre pour voir les options.', creditUnavailable: 'Impossible de charger votre solde. Réessayez avant de lancer une génération.', retryCost: 'Une nouvelle tentative réserve à nouveau le coût de génération.', jobHold: 'Les tâches en cours réservent des crédits. En cas d’échec ou d’annulation, la réserve est libérée.',
}
export function getAccountCopy(language: string | undefined): AccountCopy { return language?.startsWith('es') ? es : language?.startsWith('fr') ? fr : en }
