const en = {
  buildingContext: 'Building and sunlight',
  recoverTitle: 'Choose a new password', recoverIntro: 'Use the personal recovery link provided by your administrator.', resetPassword: 'Save new password', recoveryFailed: 'This recovery link is invalid or has expired. Ask your administrator for a new one.', recoveryDone: 'Password updated. Sign in with your new password.', recoveryHelp: 'Forgot your password? Contact the person who invited you for a recovery link.',
  workspace: 'Your workspace', projects: 'My projects', assets: 'My assets', users: 'People & invitations', demo: 'Public demo', signOut: 'Sign out', signIn: 'Sign in', loading: 'Loading your workspace…', retry: 'Try again', unavailable: 'We could not reach the server. Your work has not been changed.', expired: 'Your session has ended. Sign in again to continue.',
  loginTitle: 'A space for your ideas.', loginIntro: 'Sign in to save projects, work with your assets, and share your designs with friends.', invitedOnly: 'Access is by invitation. Ask the person who shared T3 Designer with you for your personal invitation.', email: 'Email address', password: 'Password', name: 'Your name', loginFailed: 'We could not sign you in. Check your details or contact the person who invited you.', inviteTitle: 'Welcome to T3 Designer', inviteIntro: 'Create your personal account to start designing.', acceptInvite: 'Create my account', inviteFailed: 'This invitation could not be accepted. Check your email and details, or ask for a new invitation.', invalidInvite: 'This invitation link is missing or no longer available. Open the complete link you received.', passwordHelp: 'Use at least 12 characters.', pending: 'Please wait…',
  projectsTitle: 'Make room for your next idea.', projectsIntro: 'Your projects are private. Start with the T3 demo, then make it your own.', newProject: 'Create from demo', projectName: 'Project name', defaultProject: 'My T3 project', create: 'Create project', cancel: 'Cancel', emptyTitle: 'Your first project starts here.', emptyIntro: 'Create an independent copy of the public demo to explore your own layout.', open: 'Open project', duplicate: 'Duplicate', owner: 'Owner', editor: 'Can edit', viewer: 'Can view', updated: 'Updated', revision: 'Version', noNotes: 'A fresh space to explore.',
  backProjects: 'All projects', save: 'Save changes', saved: 'Changes saved.', unsaved: 'Unsaved changes', conflict: 'This project changed in another session. Reload the latest version before editing again.', reload: 'Reload latest version', projectUnavailable: 'This project is unavailable or you no longer have access.', notes: 'Project notes', notesHelp: 'Visible to people with access to this project.', notesPlaceholder: 'Ideas, decisions, and things to try…', details: 'Project details', scene: 'Design', shared: 'Sharing', shareIntro: 'Invite an existing T3 Designer user by email. Only the owner can change access.', addMember: 'Share project', memberEmail: 'Member email', access: 'Access', remove: 'Remove access', noMembers: 'Only you have access to this project.', shareFailed: 'Could not update access. Check that this person already has an active account.', readonly: 'You have view access. Duplicate this project to create your own version.', genericError: 'That action could not be completed. Please try again.',
  peopleTitle: 'A small circle, a shared playground.', peopleIntro: 'Invite people you trust. Everyone gets their own account and private projects.', inviteEmail: 'Email to invite', invite: 'Create invitation', invitationReady: 'Invitation ready', invitationHelp: 'Send this personal link to your friend. It is shown only now and expires on', copy: 'Copy link', copied: 'Copied', copyFailed: 'Copy the link from the field below.', status: 'Status', active: 'Active', suspended: 'Suspended', suspend: 'Suspend', reactivate: 'Reactivate', revoke: 'End sessions', sessionsRevoked: 'Sessions ended.', administrator: 'Administrator', member: 'Member', invitationLink: 'Personal invitation link', ownAccount: 'Your account',
  publicAssetsTitle: 'Your own asset workshop.', publicAssetsIntro: 'Create and keep assets in your personal workspace. Sign in with your invitation to use the workshop.', exploreDemo: 'Explore the public demo', privateLabel: 'Private workspace', projectCount: 'projects', noUsers: 'No people to show.', serverUnavailable: 'The account service is unavailable. Please try again later.', discard: 'You have unsaved changes. Leave without saving?',
} as const
export type PrivateCopy = { [K in keyof typeof en]: string }
const es: PrivateCopy = {
  buildingContext: 'Edificio y luz solar',
  recoverTitle: 'Elegí una nueva contraseña', recoverIntro: 'Usá el enlace personal de recuperación que te dio tu administrador.', resetPassword: 'Guardar nueva contraseña', recoveryFailed: 'El enlace de recuperación no es válido o venció. Pedile uno nuevo a tu administrador.', recoveryDone: 'Contraseña actualizada. Iniciá sesión con tu nueva contraseña.', recoveryHelp: '¿Olvidaste tu contraseña? Pedile un enlace de recuperación a quien te invitó.',
  workspace: 'Tu espacio', projects: 'Mis proyectos', assets: 'Mis assets', users: 'Personas e invitaciones', demo: 'Demo pública', signOut: 'Cerrar sesión', signIn: 'Iniciar sesión', loading: 'Cargando tu espacio…', retry: 'Reintentar', unavailable: 'No pudimos conectar con el servidor. Tu trabajo no se modificó.', expired: 'Tu sesión terminó. Iniciá sesión de nuevo para continuar.',
  loginTitle: 'Un espacio para tus ideas.', loginIntro: 'Iniciá sesión para guardar proyectos, trabajar con tus assets y compartir diseños con amigos.', invitedOnly: 'El acceso es por invitación. Pedile tu invitación personal a quien te compartió T3 Designer.', email: 'Correo electrónico', password: 'Contraseña', name: 'Tu nombre', loginFailed: 'No pudimos iniciar sesión. Revisá tus datos o contactá a quien te invitó.', inviteTitle: 'Te damos la bienvenida a T3 Designer', inviteIntro: 'Creá tu cuenta personal para empezar a diseñar.', acceptInvite: 'Crear mi cuenta', inviteFailed: 'No pudimos aceptar esta invitación. Revisá el correo y tus datos o pedí una nueva invitación.', invalidInvite: 'Falta la invitación o el enlace ya no está disponible. Abrí el enlace completo que recibiste.', passwordHelp: 'Usá al menos 12 caracteres.', pending: 'Un momento…',
  projectsTitle: 'Hacé lugar para tu próxima idea.', projectsIntro: 'Tus proyectos son privados. Empezá con la demo T3 y hacela tuya.', newProject: 'Crear desde la demo', projectName: 'Nombre del proyecto', defaultProject: 'Mi proyecto T3', create: 'Crear proyecto', cancel: 'Cancelar', emptyTitle: 'Tu primer proyecto empieza acá.', emptyIntro: 'Creá una copia independiente de la demo pública para explorar tu propia distribución.', open: 'Abrir proyecto', duplicate: 'Duplicar', owner: 'Propietario', editor: 'Puede editar', viewer: 'Puede ver', updated: 'Actualizado', revision: 'Versión', noNotes: 'Un nuevo espacio para explorar.',
  backProjects: 'Todos los proyectos', save: 'Guardar cambios', saved: 'Cambios guardados.', unsaved: 'Cambios sin guardar', conflict: 'Este proyecto cambió en otra sesión. Cargá la última versión antes de seguir editando.', reload: 'Cargar última versión', projectUnavailable: 'Este proyecto no está disponible o ya no tenés acceso.', notes: 'Notas del proyecto', notesHelp: 'Visibles para quienes tienen acceso al proyecto.', notesPlaceholder: 'Ideas, decisiones y cosas para probar…', details: 'Detalles del proyecto', scene: 'Diseño', shared: 'Compartir', shareIntro: 'Compartí con alguien que ya tenga cuenta en T3 Designer. Solo el propietario puede cambiar los permisos.', addMember: 'Compartir proyecto', memberEmail: 'Correo de la persona', access: 'Permiso', remove: 'Quitar acceso', noMembers: 'Solo vos tenés acceso a este proyecto.', shareFailed: 'No pudimos cambiar el acceso. Revisá que esta persona ya tenga una cuenta activa.', readonly: 'Podés ver este proyecto. Duplicalo para crear tu propia versión.', genericError: 'No pudimos completar esta acción. Volvé a intentarlo.',
  peopleTitle: 'Un pequeño círculo para crear.', peopleIntro: 'Invitá a personas de confianza. Cada una tendrá su propia cuenta y proyectos privados.', inviteEmail: 'Correo para invitar', invite: 'Crear invitación', invitationReady: 'Invitación lista', invitationHelp: 'Mandale este enlace personal a tu amigo. Se muestra solo ahora y vence el', copy: 'Copiar enlace', copied: 'Copiado', copyFailed: 'Copiá el enlace del campo de abajo.', status: 'Estado', active: 'Activo', suspended: 'Suspendido', suspend: 'Suspender', reactivate: 'Reactivar', revoke: 'Cerrar sesiones', sessionsRevoked: 'Sesiones cerradas.', administrator: 'Administrador', member: 'Miembro', invitationLink: 'Enlace personal de invitación', ownAccount: 'Tu cuenta',
  publicAssetsTitle: 'Tu propio taller de assets.', publicAssetsIntro: 'Creá y guardá assets en tu espacio personal. Iniciá sesión con tu invitación para usar el taller.', exploreDemo: 'Explorar la demo pública', privateLabel: 'Espacio privado', projectCount: 'proyectos', noUsers: 'No hay personas para mostrar.', serverUnavailable: 'El servicio de cuentas no está disponible. Volvé a intentar más tarde.', discard: 'Tenés cambios sin guardar. ¿Salir sin guardarlos?',
}
const fr: PrivateCopy = {
  buildingContext: 'Bâtiment et ensoleillement',
  recoverTitle: 'Choisissez un nouveau mot de passe', recoverIntro: 'Utilisez le lien personnel de récupération fourni par votre administrateur.', resetPassword: 'Enregistrer le mot de passe', recoveryFailed: 'Ce lien est invalide ou a expiré. Demandez un nouveau lien à votre administrateur.', recoveryDone: 'Mot de passe modifié. Connectez-vous avec votre nouveau mot de passe.', recoveryHelp: 'Mot de passe oublié ? Demandez un lien de récupération à la personne qui vous a invité.',
  workspace: 'Votre espace', projects: 'Mes projets', assets: 'Mes assets', users: 'Personnes et invitations', demo: 'Démo publique', signOut: 'Se déconnecter', signIn: 'Se connecter', loading: 'Chargement de votre espace…', retry: 'Réessayer', unavailable: 'Impossible de joindre le serveur. Votre travail n’a pas été modifié.', expired: 'Votre session a expiré. Reconnectez-vous pour continuer.',
  loginTitle: 'Un espace pour vos idées.', loginIntro: 'Connectez-vous pour enregistrer vos projets, gérer vos assets et partager vos créations avec vos amis.', invitedOnly: 'L’accès se fait sur invitation. Demandez votre invitation personnelle à la personne qui vous a présenté T3 Designer.', email: 'Adresse e-mail', password: 'Mot de passe', name: 'Votre nom', loginFailed: 'Connexion impossible. Vérifiez vos informations ou contactez la personne qui vous a invité.', inviteTitle: 'Bienvenue dans T3 Designer', inviteIntro: 'Créez votre compte personnel pour commencer à concevoir.', acceptInvite: 'Créer mon compte', inviteFailed: 'Cette invitation n’a pas pu être acceptée. Vérifiez vos informations ou demandez une nouvelle invitation.', invalidInvite: 'L’invitation est absente ou indisponible. Ouvrez le lien complet que vous avez reçu.', passwordHelp: 'Utilisez au moins 12 caractères.', pending: 'Un instant…',
  projectsTitle: 'Faites place à votre prochaine idée.', projectsIntro: 'Vos projets sont privés. Partez de la démo T3 et faites-en votre propre espace.', newProject: 'Créer depuis la démo', projectName: 'Nom du projet', defaultProject: 'Mon projet T3', create: 'Créer le projet', cancel: 'Annuler', emptyTitle: 'Votre premier projet commence ici.', emptyIntro: 'Créez une copie indépendante de la démo pour explorer votre propre agencement.', open: 'Ouvrir le projet', duplicate: 'Dupliquer', owner: 'Propriétaire', editor: 'Peut modifier', viewer: 'Peut consulter', updated: 'Mis à jour', revision: 'Version', noNotes: 'Un nouvel espace à explorer.',
  backProjects: 'Tous les projets', save: 'Enregistrer', saved: 'Modifications enregistrées.', unsaved: 'Modifications non enregistrées', conflict: 'Ce projet a changé dans une autre session. Rechargez la dernière version avant de continuer.', reload: 'Charger la dernière version', projectUnavailable: 'Ce projet est indisponible ou vous n’y avez plus accès.', notes: 'Notes du projet', notesHelp: 'Visibles par les personnes ayant accès au projet.', notesPlaceholder: 'Idées, décisions et pistes à explorer…', details: 'Détails du projet', scene: 'Conception', shared: 'Partager', shareIntro: 'Partagez avec une personne ayant déjà un compte T3 Designer. Seul le propriétaire peut modifier les accès.', addMember: 'Partager le projet', memberEmail: 'Adresse e-mail du membre', access: 'Accès', remove: 'Retirer l’accès', noMembers: 'Vous seul avez accès à ce projet.', shareFailed: 'Impossible de modifier l’accès. Vérifiez que cette personne possède un compte actif.', readonly: 'Vous pouvez consulter ce projet. Dupliquez-le pour créer votre propre version.', genericError: 'Cette action n’a pas pu être effectuée. Réessayez.',
  peopleTitle: 'Un petit cercle pour créer ensemble.', peopleIntro: 'Invitez des personnes de confiance. Chacun dispose de son compte et de projets privés.', inviteEmail: 'Adresse e-mail à inviter', invite: 'Créer une invitation', invitationReady: 'Invitation prête', invitationHelp: 'Envoyez ce lien personnel à votre ami. Il est affiché uniquement maintenant et expire le', copy: 'Copier le lien', copied: 'Copié', copyFailed: 'Copiez le lien dans le champ ci-dessous.', status: 'Statut', active: 'Actif', suspended: 'Suspendu', suspend: 'Suspendre', reactivate: 'Réactiver', revoke: 'Fermer les sessions', sessionsRevoked: 'Sessions fermées.', administrator: 'Administrateur', member: 'Membre', invitationLink: 'Lien personnel d’invitation', ownAccount: 'Votre compte',
  publicAssetsTitle: 'Votre propre atelier d’assets.', publicAssetsIntro: 'Créez et conservez vos assets dans votre espace personnel. Connectez-vous avec votre invitation pour utiliser l’atelier.', exploreDemo: 'Explorer la démo publique', privateLabel: 'Espace privé', projectCount: 'projets', noUsers: 'Aucune personne à afficher.', serverUnavailable: 'Le service de comptes est indisponible. Réessayez plus tard.', discard: 'Des modifications ne sont pas enregistrées. Quitter sans enregistrer ?',
}
export function getPrivateCopy(language: string | undefined): PrivateCopy { return language === 'es' ? es : language === 'fr' ? fr : en }
