const en = {
  title: 'Generate a 3D concept', intro: 'Describe your idea and provide the dimensions and location to create an editable private project.',
  limit: 'This is an approximate concept: one modeled floor and a simple building envelope. Rooms, walls and openings are AI estimates. It is not a measured survey, cadastral record or construction plan.',
  kind: 'What would you like to generate?', project: 'Project', apartment: 'Apartment', building: 'Building', name: 'Project name', prompt: 'Describe your project', promptHelp: 'Include the rooms, circulation, openings and priorities you want. Use at least 10 characters.',
  dimensions: 'Dimensions you provide', width: 'Width (m)', depth: 'Depth (m)', storeyHeight: 'Height per floor (m)', floors: 'Number of floors', location: 'Location for sunlight', latitude: 'Latitude', longitude: 'Longitude', timeZone: 'IANA time zone', locationHelp: 'Use the coordinates and time zone of the building. These are supplied by you, not verified property data.',
  submit: 'Generate concept', queued: 'Queued', running: 'Generating', completed: 'Ready', failed: 'Failed', cancelled: 'Canceled', history: 'Your concept generations', empty: 'Your generated concepts will appear here.', open: 'Open project', cancel: 'Cancel generation', cancelHelp: 'The reservation is released when a generation fails or is canceled, subject to the original credit expiry.', unavailable: 'Concept generation is currently unavailable. Your existing projects remain accessible.', invalidTimeZone: 'Enter a valid IANA time zone, such as Europe/Paris.', accepted: 'Generation requested. You can follow its progress here and return later.', retry: 'Refresh generations',
} as const
export type GenerationCopy = { [K in keyof typeof en]: string }
const es: GenerationCopy = {
  title: 'Generar un concepto 3D', intro: 'Describí tu idea e indicá las dimensiones y la ubicación para crear un proyecto privado editable.',
  limit: 'Es un concepto aproximado: una planta modelada y una envolvente simple del edificio. Ambientes, paredes y aberturas son estimaciones de IA. No es un relevamiento medido, un registro catastral ni un plano de obra.',
  kind: '¿Qué querés generar?', project: 'Proyecto', apartment: 'Departamento', building: 'Edificio', name: 'Nombre del proyecto', prompt: 'Describí tu proyecto', promptHelp: 'Incluí los ambientes, la circulación, las aberturas y tus prioridades. Usá al menos 10 caracteres.',
  dimensions: 'Dimensiones que aportás', width: 'Ancho (m)', depth: 'Profundidad (m)', storeyHeight: 'Altura por planta (m)', floors: 'Cantidad de plantas', location: 'Ubicación para la luz solar', latitude: 'Latitud', longitude: 'Longitud', timeZone: 'Zona horaria IANA', locationHelp: 'Usá las coordenadas y la zona horaria del edificio. Son datos que aportás vos, no datos verificados de la propiedad.',
  submit: 'Generar concepto', queued: 'En cola', running: 'Generando', completed: 'Listo', failed: 'Falló', cancelled: 'Cancelado', history: 'Tus conceptos generados', empty: 'Tus conceptos generados van a aparecer acá.', open: 'Abrir proyecto', cancel: 'Cancelar generación', cancelHelp: 'Si la generación falla o se cancela, se libera la reserva según el vencimiento original de los créditos.', unavailable: 'La generación de conceptos no está disponible en este momento. Podés seguir usando tus proyectos.', invalidTimeZone: 'Ingresá una zona horaria IANA válida, por ejemplo Europe/Paris.', accepted: 'Generación solicitada. Podés seguir el progreso acá y volver más tarde.', retry: 'Actualizar generaciones',
}
const fr: GenerationCopy = {
  title: 'Générer un concept 3D', intro: 'Décrivez votre idée et indiquez les dimensions et l’emplacement pour créer un projet privé modifiable.',
  limit: 'Il s’agit d’un concept approximatif : un étage modélisé et une enveloppe simple du bâtiment. Les pièces, murs et ouvertures sont des estimations IA. Ce n’est ni un relevé mesuré, ni un document cadastral, ni un plan de construction.',
  kind: 'Que souhaitez-vous générer ?', project: 'Projet', apartment: 'Appartement', building: 'Bâtiment', name: 'Nom du projet', prompt: 'Décrivez votre projet', promptHelp: 'Précisez les pièces, la circulation, les ouvertures et vos priorités. Utilisez au moins 10 caractères.',
  dimensions: 'Dimensions fournies', width: 'Largeur (m)', depth: 'Profondeur (m)', storeyHeight: 'Hauteur par étage (m)', floors: 'Nombre d’étages', location: 'Emplacement pour l’ensoleillement', latitude: 'Latitude', longitude: 'Longitude', timeZone: 'Fuseau horaire IANA', locationHelp: 'Utilisez les coordonnées et le fuseau du bâtiment. Ces informations sont fournies par vous et ne sont pas des données immobilières vérifiées.',
  submit: 'Générer le concept', queued: 'En attente', running: 'Génération en cours', completed: 'Prêt', failed: 'Échec', cancelled: 'Annulé', history: 'Vos concepts générés', empty: 'Vos concepts générés apparaîtront ici.', open: 'Ouvrir le projet', cancel: 'Annuler la génération', cancelHelp: 'En cas d’échec ou d’annulation, la réserve est libérée selon l’expiration initiale des crédits.', unavailable: 'La génération de concepts est indisponible. Vos projets restent accessibles.', invalidTimeZone: 'Saisissez un fuseau IANA valide, par exemple Europe/Paris.', accepted: 'Génération demandée. Suivez sa progression ici ou revenez plus tard.', retry: 'Actualiser les générations',
}
export function getGenerationCopy(language: string): GenerationCopy { return language.startsWith('es') ? es : language.startsWith('fr') ? fr : en }
