export const walkCopy = {
  es: {
    title: 'Recorrido en primera persona', launch: 'Recorrer esta versión', eyebrow: 'A escala humana',
    intro: 'Entrá, mirá alrededor y descubrí cómo se siente el espacio.', back: 'Volver al diseño',
    start: 'Entrar al departamento', resume: 'Continuar recorrido', pause: 'Pausar', paused: 'Listo para recorrer', live: 'Explorando',
    loading: 'Preparando escena…', fallback: 'El recorrido necesita WebGL 2. Probá con un navegador compatible y la aceleración gráfica activada.',
    move: 'Caminar', look: 'Mirar', run: 'Correr', crouch: 'Agacharse', jump: 'Saltar', space: 'Espacio', release: 'Pausar y liberar cursor',
    interact: 'Interactuar', openDoor: 'Abrir puerta', closeDoor: 'Cerrar puerta', doorBlocked: 'Dejá espacio para mover la puerta.',
    mouse: 'Mouse capturado', mouseFree: 'Mouse sin clic · bordes para seguir girando', mouseTouch: 'Arrastrá para mirar', keyboard: 'WASD: caminar · Flechas: mirar', turn: 'Girar',
    hint: 'Al entrar, mové el mouse para mirar sin mantener clic. Si el navegador no captura el cursor, acercalo a los bordes para seguir girando. Mirá una puerta cercana y pulsá E para abrirla o cerrarla. En pantalla táctil, arrastrá para mirar y tocá la acción de la puerta. Escape pausa el recorrido.',
    settings: 'Preparar el paseo', room: 'Punto de inicio', entrance: 'Entrada segura', reset: 'Volver al inicio',
    height: 'Altura de los ojos', sensitivity: 'Sensibilidad del mouse', fov: 'Campo de visión',
    date: 'Fecha', time: 'Hora local', artificial: 'Luces del diseño', torch: 'Linterna de ayuda',
    controls: 'Controles en pantalla', viewerControls: 'Controles del visor', fullscreen: 'Pantalla completa', exitFullscreen: 'Salir de pantalla completa',
    map: 'Tu ubicación', version: 'Versión de la visita', reference: 'Departamento de referencia',
    draft: 'Incluye el estado actual del diseño. Los ajustes del paseo son temporales.',
    notice: 'Geometría y colisiones aproximadas. Las puertas se pueden abrir y cerrar durante el paseo sin cambiar el diseño. Recorrido limitado al interior; iluminación orientativa.',
    noSpawn: 'No hay espacio libre para iniciar aquí. Elegí otra habitación o despejá la distribución.',
    invalidTime: 'Esta hora no existe por el cambio de horario. Elegí otra.', repeatedTime: 'Hora repetida: se usa la primera ocurrencia.',
    forward: 'Avanzar', backward: 'Retroceder', left: 'Mover a la izquierda', right: 'Mover a la derecha', turnLeft: 'Girar a la izquierda', turnRight: 'Girar a la derecha',
    savedSun: 'Restaurar hora del diseño', fullscreenError: 'El navegador no pudo abrir la pantalla completa.',
  },
  en: {
    title: 'First-person walkthrough', launch: 'Walk through this version', eyebrow: 'At human scale',
    intro: 'Step inside, look around and discover how the space feels.', back: 'Back to design',
    start: 'Enter the apartment', resume: 'Resume walkthrough', pause: 'Pause', paused: 'Ready to explore', live: 'Exploring',
    loading: 'Preparing scene…', fallback: 'This walkthrough needs WebGL 2. Try a compatible browser with graphics acceleration enabled.',
    move: 'Walk', look: 'Look around', run: 'Run', crouch: 'Crouch', jump: 'Jump', space: 'Space', release: 'Pause and release cursor',
    interact: 'Interact', openDoor: 'Open door', closeDoor: 'Close door', doorBlocked: 'Leave room for the door to move.',
    mouse: 'Mouse captured', mouseFree: 'Move mouse to look · edges keep turning', mouseTouch: 'Drag to look', keyboard: 'WASD: move · Arrows: look', turn: 'Turn',
    hint: 'Once inside, move the mouse to look without holding a button. If the browser cannot capture it, move toward an edge to keep turning. Look at a nearby door and press E to open or close it. On touchscreens, drag to look and tap the door action. Escape pauses the walkthrough.',
    settings: 'Set up your visit', room: 'Starting point', entrance: 'Safe entrance', reset: 'Return to start',
    height: 'Eye height', sensitivity: 'Mouse sensitivity', fov: 'Field of view',
    date: 'Date', time: 'Local time', artificial: 'Design lights', torch: 'Help flashlight',
    controls: 'On-screen controls', viewerControls: 'Viewer controls', fullscreen: 'Fullscreen', exitFullscreen: 'Exit fullscreen',
    map: 'Your location', version: 'Visit version', reference: 'Reference apartment',
    draft: 'Includes the current design state. Walkthrough adjustments are temporary.',
    notice: 'Approximate geometry and collisions. Open and close doors during the visit without changing the design. Interior only; illustrative lighting.',
    noSpawn: 'No free space to start here. Choose another room or clear the layout.',
    invalidTime: 'This time does not exist because the clocks change. Choose another.', repeatedTime: 'Repeated time: using the first occurrence.',
    forward: 'Move forward', backward: 'Move backward', left: 'Move left', right: 'Move right', turnLeft: 'Turn left', turnRight: 'Turn right',
    savedSun: 'Restore design time', fullscreenError: 'The browser could not open fullscreen.',
  },
  fr: {
    title: 'Visite à la première personne', launch: 'Visiter cette version', eyebrow: 'À échelle humaine',
    intro: 'Entrez, regardez autour de vous et découvrez les volumes.', back: 'Retour au plan',
    start: 'Entrer dans l’appartement', resume: 'Reprendre la visite', pause: 'Pause', paused: 'Prêt pour la visite', live: 'En visite',
    loading: 'Préparation de la scène…', fallback: 'La visite nécessite WebGL 2. Essayez un navigateur compatible avec l’accélération graphique activée.',
    move: 'Marcher', look: 'Regarder', run: 'Courir', crouch: 'S’accroupir', jump: 'Sauter', space: 'Espace', release: 'Pause et libérer le curseur',
    interact: 'Interagir', openDoor: 'Ouvrir la porte', closeDoor: 'Fermer la porte', doorBlocked: 'Laissez de la place pour déplacer la porte.',
    mouse: 'Souris capturée', mouseFree: 'Souris sans clic · bords pour continuer à tourner', mouseTouch: 'Glisser pour regarder', keyboard: 'WASD : marcher · Flèches : regarder', turn: 'Tourner',
    hint: 'Une fois entré, bougez la souris pour regarder sans maintenir de bouton. Si le navigateur ne la capture pas, approchez un bord pour continuer à tourner. Regardez une porte proche et appuyez sur E pour l’ouvrir ou la fermer. Sur écran tactile, glissez pour regarder et touchez l’action de la porte. Échap met la visite en pause.',
    settings: 'Préparer la visite', room: 'Point de départ', entrance: 'Entrée dégagée', reset: 'Revenir au départ',
    height: 'Hauteur des yeux', sensitivity: 'Sensibilité de la souris', fov: 'Champ de vision',
    date: 'Date', time: 'Heure locale', artificial: 'Lumières du projet', torch: 'Lampe de secours',
    controls: 'Commandes à l’écran', viewerControls: 'Commandes de la vue', fullscreen: 'Plein écran', exitFullscreen: 'Quitter le plein écran',
    map: 'Votre position', version: 'Version visitée', reference: 'Appartement de référence',
    draft: 'Inclut l’état actuel du projet. Les réglages de visite sont temporaires.',
    notice: 'Géométrie et collisions approximatives. Ouvrez et fermez les portes pendant la visite sans modifier le projet. Intérieur uniquement ; éclairage indicatif.',
    noSpawn: 'Aucun espace libre ici. Choisissez une autre pièce ou dégagez l’aménagement.',
    invalidTime: 'Cette heure n’existe pas à cause du changement d’heure. Choisissez-en une autre.', repeatedTime: 'Heure répétée : première occurrence utilisée.',
    forward: 'Avancer', backward: 'Reculer', left: 'Aller à gauche', right: 'Aller à droite', turnLeft: 'Tourner à gauche', turnRight: 'Tourner à droite',
    savedSun: 'Rétablir l’heure du projet', fullscreenError: 'Le navigateur n’a pas pu ouvrir le plein écran.',
  },
} as const
