import { expect, test } from '@playwright/test'

test.use({ locale: 'en-GB' })

test('building camera and layers float over the full-width scene and studies stay inside the settings panel', async ({ page }) => {
  await page.goto('/#building')
  const viewport = page.locator('.building-viewport')
  const toolbar = viewport.locator('.building-studio-toolbar')
  const inspector = page.getByRole('dialog', { name: 'Building controls', exact: true })
  await expect(toolbar).toBeVisible({ timeout: 20_000 })
  await expect(toolbar).toHaveCount(1)
  await expect(inspector).toHaveCount(0)
  await expect(toolbar.getByRole('button', { name: 'Floor plan', exact: true })).toHaveCount(0)
  await expect(toolbar.getByRole('button', { name: 'Solar energy', exact: true })).toHaveCount(0)
  await expect(toolbar.getByRole('button', { name: /solar panels/i })).toHaveCount(0)
  await expect(viewport.getByRole('checkbox', { name: 'Nearby buildings', exact: true })).toBeVisible()
  const panels = viewport.locator('.building-layers').getByRole('checkbox', { name: 'Solar panels', exact: true })
  await expect(panels).not.toBeChecked()
  const original = await viewport.boundingBox()
  const tools = await toolbar.boundingBox()
  expect(tools!.y).toBeGreaterThan(original!.y)
  expect(tools!.y + tools!.height).toBeLessThan(original!.y + original!.height)

  await panels.check()
  await toolbar.getByRole('button', { name: 'Show controls', exact: true }).click()
  await expect(inspector).toBeVisible()
  expect((await viewport.boundingBox())!.width).toBe(original!.width)
  await page.locator('#solar-date').fill('2026-12-21')
  await inspector.getByRole('button', { name: 'Solar energy', exact: true }).click()
  await expect(inspector.locator('.building-energy-study')).toBeVisible()
  await expect(page.locator('.building-studio > .building-energy-study')).toHaveCount(0)
  await expect(panels).toBeChecked()
  await page.keyboard.press('Escape')
  await panels.uncheck()
  await toolbar.getByRole('button', { name: 'Show controls', exact: true }).click()
  await expect(inspector.getByRole('button', { name: 'Solar energy', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await inspector.getByRole('button', { name: 'Light and surroundings', exact: true }).click()
  await expect(page.locator('#solar-date')).toHaveValue('2026-12-21')
  await expect(panels).not.toBeChecked()
  await page.keyboard.press('Escape')
  await expect(inspector).toHaveCount(0)
  await expect(toolbar.getByRole('button', { name: 'Show controls', exact: true })).toBeFocused()
  await expect(toolbar.getByRole('button', { name: 'Map', exact: true })).toHaveCount(1)
})

for (const mode of ['Light and surroundings', 'Solar energy']) {
  test(`expanded ${mode.toLowerCase()} keeps a full scene and closes the overlay before fullscreen on Escape`, async ({ page }) => {
    await page.goto('/#building')
    const toolbar = page.locator('.building-studio-toolbar')
    await toolbar.getByRole('button', { name: 'Show controls', exact: true }).click()
    await page.getByRole('dialog', { name: 'Building controls', exact: true }).getByRole('button', { name: mode, exact: true }).click()
    const expand = toolbar.getByRole('button', { name: 'Expand view', exact: true })
    await expand.click()
    const viewer = page.getByRole('dialog', { name: 'Building viewer', exact: true })
    await expect(viewer).toBeVisible()
    await expect(viewer).toHaveAttribute('aria-modal', 'true')
    await expect(page.locator('#building-inspector')).toHaveCount(0)
    await expect(page.locator('.workspace-switcher')).toHaveJSProperty('inert', true)
    await expect(page.locator('.app-header')).toHaveJSProperty('inert', true)
    await expect.poll(() => viewer.evaluate(node => Math.round(node.getBoundingClientRect().height) === window.innerHeight)).toBe(true)
    await viewer.locator('.building-layers input').last().focus()
    await page.keyboard.press('Tab')
    await expect(viewer.getByRole('button', { name: 'Perspective', exact: true })).toBeFocused()
    await viewer.getByRole('button', { name: 'Show controls', exact: true }).click()
    const inspector = page.getByRole('dialog', { name: 'Building controls', exact: true })
    await expect(inspector).toBeVisible()
    if (mode === 'Solar energy') await expect(inspector.locator('.building-energy-study')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(inspector).toHaveCount(0)
    await expect(viewer).toBeVisible()
    await expect(viewer.getByRole('button', { name: 'Show controls', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(viewer).toHaveCount(0)
    await expect(expand).toBeFocused()
    await expect(page.locator('.app-header')).toHaveJSProperty('inert', false)
    await expect(page.getByRole('navigation', { name: 'Choose project view' })).toBeVisible()
  })
}

test('mobile overlays and their energy workbench remain inside the viewer in both study modes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#building')
  const toolbar = page.locator('.building-studio-toolbar')
  for (const mode of ['Light and surroundings', 'Solar energy']) {
    await toolbar.getByRole('button', { name: 'Show controls', exact: true }).click()
    const inspector = page.getByRole('dialog', { name: 'Building controls', exact: true })
    await inspector.getByRole('button', { name: mode, exact: true }).click()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
    const viewportBox = (await page.locator('.building-viewport').boundingBox())!
    const panelBox = (await inspector.boundingBox())!
    expect(panelBox.x).toBeGreaterThanOrEqual(viewportBox.x)
    expect(panelBox.x + panelBox.width).toBeLessThanOrEqual(viewportBox.x + viewportBox.width + 1)
    expect(panelBox.y + panelBox.height).toBeLessThanOrEqual(viewportBox.y + viewportBox.height + 1)
    await expect.poll(() => inspector.locator('.viewer-panel-body').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    await toolbar.getByRole('button', { name: 'Expand view', exact: true }).click()
    const viewer = page.getByRole('dialog', { name: 'Building viewer', exact: true })
    await viewer.getByRole('button', { name: 'Show controls', exact: true }).click()
    await expect(inspector).toBeVisible()
    await expect.poll(() => viewer.evaluate(node => node.scrollWidth <= window.innerWidth + 1)).toBe(true)
    await page.keyboard.press('Escape')
    await page.keyboard.press('Escape')
  }
})
