export const energyIntegrationCopy = {
  es: {
    modeLabel: 'Estudios del edificio', light: 'Luz y entorno', energy: 'Energía solar',
    title: 'El techo también produce.', scope: 'Instalación del edificio',
    intro: 'Explorá una instalación hipotética en la cubierta y su generación, ahorro y retorno.',
    planned: 'Paneles representados', capacity: 'Potencia instalada en el escenario',
    open: 'Ver generación y retorno ↓', roof: 'Ver cubierta', panels: 'Paneles solares',
    roofHint: 'Cubierta y soportes aproximados. La viabilidad estructural, los obstáculos y la autorización de uso del techo quedan por verificar.',
    save: 'Guardar escenario en este navegador', saved: 'Escenario guardado en este navegador.',
    dirty: 'Cambios sin guardar.', default: 'Escenario de ejemplo. Podés guardar tus ajustes en este navegador.',
    invalid: 'El escenario guardado no es válido. Se cargó el ejemplo.',
    unavailable: 'No se pudo guardar o recuperar el escenario en este navegador. Los ajustes siguen disponibles durante esta sesión.',
    reset: 'Restablecer ejemplo', revert: 'Descartar cambios', privateTitle: 'Energía solar del edificio',
    privateHint: 'Estos ajustes se guardan con el proyecto y se comparten entre todas sus variantes del departamento. Usá «Guardar cambios» para conservarlos.',
    localDate: 'Fecha del estudio energético', localTime: 'Hora local del estudio energético',
    dateError: 'Esa hora local no existe por el cambio de horario. Elegí otra hora.',
    repeatedTime: 'Esta hora ocurre dos veces por el cambio de horario; se usa la primera.',
  },
  en: {
    modeLabel: 'Building studies', light: 'Light and surroundings', energy: 'Solar energy',
    title: 'Put the roof to work.', scope: 'Building installation',
    intro: 'Explore a hypothetical rooftop array, its generation, savings and payback.',
    planned: 'Panels shown', capacity: 'Installed capacity in this scenario',
    open: 'Explore generation and payback ↓', roof: 'View roof', panels: 'Solar panels',
    roofHint: 'The roof and supports are approximate. Structural feasibility, obstacles and permission to use the roof remain to be checked.',
    save: 'Save scenario in this browser', saved: 'Scenario saved in this browser.',
    dirty: 'Unsaved changes.', default: 'Example scenario. You can save your settings in this browser.',
    invalid: 'The saved scenario is invalid. The example was loaded.',
    unavailable: 'The scenario could not be saved or recovered in this browser. Your settings remain available during this session.',
    reset: 'Reset example', revert: 'Discard changes', privateTitle: 'Building solar energy',
    privateHint: 'These settings are saved with the project and shared across all its apartment variants. Use “Save changes” to keep them.',
    localDate: 'Energy study date', localTime: 'Energy study local time',
    dateError: 'This local time does not exist because the clocks change. Choose another time.',
    repeatedTime: 'This time occurs twice because the clocks change; the first occurrence is used.',
  },
  fr: {
    modeLabel: 'Études du bâtiment', light: 'Lumière et environnement', energy: 'Énergie solaire',
    title: 'Un toit qui produit.', scope: 'Installation du bâtiment',
    intro: 'Explorez une installation hypothétique en toiture, sa production, ses économies et sa rentabilité.',
    planned: 'Panneaux représentés', capacity: 'Puissance installée dans ce scénario',
    open: 'Voir la production et la rentabilité ↓', roof: 'Voir la toiture', panels: 'Panneaux solaires',
    roofHint: 'Toiture et supports approximatifs. La faisabilité structurelle, les obstacles et l’autorisation d’utiliser la toiture restent à vérifier.',
    save: 'Enregistrer le scénario dans ce navigateur', saved: 'Scénario enregistré dans ce navigateur.',
    dirty: 'Modifications non enregistrées.', default: 'Scénario d’exemple. Vous pouvez enregistrer vos réglages dans ce navigateur.',
    invalid: 'Le scénario enregistré est invalide. L’exemple a été chargé.',
    unavailable: 'Impossible d’enregistrer ou de récupérer le scénario dans ce navigateur. Vos réglages restent disponibles pendant cette session.',
    reset: 'Rétablir l’exemple', revert: 'Annuler les modifications', privateTitle: 'Énergie solaire du bâtiment',
    privateHint: 'Ces réglages sont enregistrés avec le projet et partagés par toutes ses variantes d’appartement. Utilisez « Enregistrer les modifications » pour les conserver.',
    localDate: 'Date de l’étude énergétique', localTime: 'Heure locale de l’étude énergétique',
    dateError: 'Cette heure locale n’existe pas à cause du changement d’heure. Choisissez une autre heure.',
    repeatedTime: 'Cette heure existe deux fois à cause du changement d’heure ; la première occurrence est utilisée.',
  },
} as const
