const en = {
  title: 'Arrange your apartment', subtitle: 'Explore a layout, keep what works, and try another idea.',
  architecture: 'Apartment variants', layouts: 'Furniture layouts', original: 'Original apartment', initial: 'Initial layout',
  copyName: 'Copy name', copyPlaceholder: 'e.g. Dressing room · option B', duplicateArchitecture: 'Duplicate variant', duplicateLayout: 'Duplicate layout',
  variantHint: 'Walls belong to the variant. Each layout keeps its furniture, finishes, openings and lights.', layoutHint: 'Duplicate before trying a different arrangement.',
  three: '3D', top: 'Floor plan', undo: 'Undo', redo: 'Redo', snap: 'Grid snap', free: 'Free',
  objects: 'Placed objects', selected: 'Selected object', empty: 'Select an object in the scene or in the list.',
  fixed: 'Fixed', movable: 'Movable', fixedHint: 'Installed element. Its position is fixed in furniture layouts.', movableHint: 'Movable object. Drag it or use the position controls.',
  x: 'X (m)', y: 'Height (m)', z: 'Z (m)', rotation: 'Rotation (°)', rotate: 'Rotate 90°', duplicate: 'Duplicate object', remove: 'Remove object',
  catalog: 'Project library', asset: 'Object to place', room: 'Place in room', add: 'Place object',
  catalogHint: 'Add generated models from the project asset library. Each placement uses the exact model version attached to the project.',
  partition: 'Try a divider', partitionHint: 'A proposed wall in this variant, shared by its furniture layouts. Existing room labels and areas stay unchanged.',
  fromX: 'Start X (m)', fromZ: 'Start Z (m)', toX: 'End X (m)', toZ: 'End Z (m)', height: 'Wall height (m)', thickness: 'Thickness (m)',
  addPartition: 'Add divider', removePartition: 'Remove divider', partitions: 'Proposed dividers',
  shortcuts: 'Select + drag: move · arrows: nudge · R: rotate · Delete: remove · ⌘/Ctrl Z: undo',
  camera: 'Drag empty space: orbit · wheel: zoom · right drag: pan',
  saveHint: 'Changes are a draft until you save the project.', readonly: 'Read-only project',
  error: 'That change is not valid. Check positions and dimensions, keep objects and lights inside the apartment, and use at most eight light sources.',
  nameError: 'Enter a name for the copy.', copied: 'Copy created.',
  approximation: 'Estimated dimensions. Collision detection and structural checks are not included.',
  noAssets: 'No models available in this project.', rename: 'Rename', name: 'Name', apply: 'Apply name',
}
const es: typeof en = {
  title: 'Diseñá tu departamento', subtitle: 'Probá una distribución, guardá lo que funciona y explorá otra idea.',
  architecture: 'Variantes del departamento', layouts: 'Distribuciones', original: 'Departamento original', initial: 'Distribución inicial',
  copyName: 'Nombre de la copia', copyPlaceholder: 'Ej. Cambiador · opción B', duplicateArchitecture: 'Duplicar variante', duplicateLayout: 'Duplicar distribución',
  variantHint: 'Las paredes pertenecen a la variante. Cada distribución guarda sus muebles, acabados, aberturas y luces.', layoutHint: 'Duplicá antes de probar otra disposición.',
  three: '3D', top: 'Plano', undo: 'Deshacer', redo: 'Rehacer', snap: 'Ajuste a grilla', free: 'Libre',
  objects: 'Objetos colocados', selected: 'Objeto seleccionado', empty: 'Seleccioná un objeto en la escena o en la lista.',
  fixed: 'Fijo', movable: 'Movible', fixedHint: 'Elemento instalado. Su posición es fija en las distribuciones.', movableHint: 'Objeto movible. Arrastralo o usá los controles de posición.',
  x: 'X (m)', y: 'Altura (m)', z: 'Z (m)', rotation: 'Rotación (°)', rotate: 'Rotar 90°', duplicate: 'Duplicar objeto', remove: 'Quitar objeto',
  catalog: 'Biblioteca del proyecto', asset: 'Objeto para colocar', room: 'Colocar en ambiente', add: 'Colocar objeto',
  catalogHint: 'Añadí modelos generados desde la biblioteca de assets del proyecto. Cada colocación usa la versión exacta del modelo incorporado.',
  partition: 'Probar un divisor', partitionHint: 'Una pared propuesta en esta variante, compartida por sus distribuciones. Los nombres y superficies de los ambientes se conservan.',
  fromX: 'Inicio X (m)', fromZ: 'Inicio Z (m)', toX: 'Fin X (m)', toZ: 'Fin Z (m)', height: 'Altura del muro (m)', thickness: 'Espesor (m)',
  addPartition: 'Añadir divisor', removePartition: 'Quitar divisor', partitions: 'Divisores propuestos',
  shortcuts: 'Seleccioná y arrastrá: mover · flechas: ajustar · R: rotar · Supr: quitar · ⌘/Ctrl Z: deshacer',
  camera: 'Arrastrá el fondo: orbitar · rueda: zoom · botón derecho: desplazar',
  saveHint: 'Los cambios son un borrador hasta que guardes el proyecto.', readonly: 'Proyecto de solo lectura',
  error: 'Ese cambio no es válido. Revisá posiciones y medidas, mantené objetos y luces dentro del departamento y usá como máximo ocho fuentes de luz.',
  nameError: 'Escribí un nombre para la copia.', copied: 'Copia creada.',
  approximation: 'Medidas estimadas. No incluye detección de colisiones ni comprobación estructural.',
  noAssets: 'Todavía no hay modelos en este proyecto.', rename: 'Renombrar', name: 'Nombre', apply: 'Aplicar nombre',
}
const fr: typeof en = {
  title: 'Aménagez votre appartement', subtitle: 'Explorez un agencement, gardez ce qui fonctionne et essayez une autre idée.',
  architecture: 'Variantes de l’appartement', layouts: 'Agencements', original: 'Appartement original', initial: 'Agencement initial',
  copyName: 'Nom de la copie', copyPlaceholder: 'Ex. Dressing · option B', duplicateArchitecture: 'Dupliquer la variante', duplicateLayout: 'Dupliquer l’agencement',
  variantHint: 'Les murs appartiennent à la variante. Chaque agencement conserve ses meubles, finitions, ouvertures et lumières.', layoutHint: 'Dupliquez avant d’essayer une autre disposition.',
  three: '3D', top: 'Plan', undo: 'Annuler', redo: 'Rétablir', snap: 'Grille', free: 'Libre',
  objects: 'Objets placés', selected: 'Objet sélectionné', empty: 'Sélectionnez un objet dans la scène ou dans la liste.',
  fixed: 'Fixe', movable: 'Mobile', fixedHint: 'Élément installé. Sa position est fixe dans les agencements.', movableHint: 'Objet mobile. Déplacez-le ou utilisez les réglages de position.',
  x: 'X (m)', y: 'Hauteur (m)', z: 'Z (m)', rotation: 'Rotation (°)', rotate: 'Tourner de 90°', duplicate: 'Dupliquer l’objet', remove: 'Retirer l’objet',
  catalog: 'Bibliothèque du projet', asset: 'Objet à placer', room: 'Placer dans la pièce', add: 'Placer l’objet',
  catalogHint: 'Ajoutez des modèles générés depuis la bibliothèque du projet. Chaque placement utilise la version exacte du modèle associé.',
  partition: 'Essayer une cloison', partitionHint: 'Un mur proposé dans cette variante, partagé par ses agencements. Les noms et surfaces des pièces sont conservés.',
  fromX: 'Début X (m)', fromZ: 'Début Z (m)', toX: 'Fin X (m)', toZ: 'Fin Z (m)', height: 'Hauteur du mur (m)', thickness: 'Épaisseur (m)',
  addPartition: 'Ajouter une cloison', removePartition: 'Retirer la cloison', partitions: 'Cloisons proposées',
  shortcuts: 'Sélectionner et glisser : déplacer · flèches : ajuster · R : tourner · Suppr : retirer · ⌘/Ctrl Z : annuler',
  camera: 'Glisser le fond : orbiter · molette : zoomer · clic droit : déplacer',
  saveHint: 'Les modifications restent un brouillon jusqu’à l’enregistrement du projet.', readonly: 'Projet en lecture seule',
  error: 'Modification invalide. Vérifiez les positions et dimensions, gardez les objets et lumières dans l’appartement et limitez-vous à huit sources lumineuses.',
  nameError: 'Saisissez un nom pour la copie.', copied: 'Copie créée.',
  approximation: 'Dimensions estimées. Sans détection des collisions ni vérification structurelle.',
  noAssets: 'Aucun modèle disponible dans ce projet.', rename: 'Renommer', name: 'Nom', apply: 'Appliquer le nom',
}
export const editorCopy = { en, es, fr }
