const en = {
  title: 'Finishes & lighting', subtitle: 'Explore the atmosphere of your apartment.',
  materials: 'Walls & floors', openings: 'Doors & windows', lighting: 'Lighting',
  walls: 'Walls', wall: 'Wall', allWalls: 'All walls', wallColor: 'Wall color', exterior: 'Exterior', interior: 'Interior',
  floors: 'Floors', floorRoom: 'Floor in room', allRooms: 'All rooms', floorMaterial: 'Floor finish', floorColor: 'Floor color',
  parquet: 'Wood parquet', slate: 'Slate', ivoryTile: 'Ivory tile', entryTile: 'Entrance tile', concrete: 'Concrete',
  white: 'Chalk', cream: 'Linen', sand: 'Sand', sage: 'Sage', blue: 'Blue gray', clay: 'Clay',
  color: 'Custom color', mixed: 'Several finishes selected. Your next change applies to every selected surface.', reset: 'Restore original',
  doors: 'Doors', door: 'Door', doorStyle: 'Door style', panel: 'Solid panel', glazed: 'Glazed', passage: 'Open passage',
  doorColor: 'Door finish', openness: 'Door opening', closed: 'Closed', open: 'Open', noDoors: 'This variant has no doors.',
  windows: 'Windows', window: 'Window', windowStyle: 'Window style', casement: 'Casement', sliding: 'Sliding', fixed: 'Fixed',
  frameColor: 'Frame color', covering: 'Window dressing', none: 'None', curtain: 'Curtains', blind: 'Roller blind', shutter: 'Shutters',
  coveringColor: 'Fabric or shutter color', closure: 'Window dressing closure', noWindows: 'This variant has no windows.',
  openingHint: 'Styles keep the existing opening dimensions. Window dressings also affect the daylight preview.',
  naturalEnabled: 'Natural light', artificialEnabled: 'Artificial lights', lightingHint: 'An estimated visual preview. Brightness, materials and light transmission are not calibrated measurements.',
  fixedLights: 'Room light points', fixedLight: 'Light point', lightRoom: 'Room for a new light', addLight: 'Add light point', removeLight: 'Remove light point',
  chooseLight: 'Light point to edit', noLights: 'Add a light point for a ceiling, wall or other position in the room.',
  lightName: 'Light name', enabled: 'Light on', temperature: 'Color temperature', brightness: 'Light output', warm: 'Warm', neutral: 'Neutral white', cool: 'Cool white',
  x: 'X (m)', y: 'Height (m)', z: 'Z (m)', sourcePosition: 'Light position',
  fixtureLight: 'Light from an object', selectFixture: 'Select a lamp or another object in the editor to add its light source.',
  emitLight: 'This object emits light', fixtureHint: 'Place the source at the bulb. It moves and rotates with this object.',
  offsetX: 'Local X (m)', offsetY: 'Height from base (m)', offsetZ: 'Local Z (m)',
  lightLimit: 'Up to 8 light sources per layout, including lights from objects.',
  saveHint: 'Each layout keeps its own finishes and lights. Save the project to keep your changes.',
}
const es: typeof en = {
  title: 'Terminaciones e iluminación', subtitle: 'Explorá el ambiente de tu departamento.',
  materials: 'Paredes y pisos', openings: 'Puertas y ventanas', lighting: 'Iluminación',
  walls: 'Paredes', wall: 'Pared', allWalls: 'Todas las paredes', wallColor: 'Color de pared', exterior: 'Exterior', interior: 'Interior',
  floors: 'Pisos', floorRoom: 'Piso del ambiente', allRooms: 'Todos los ambientes', floorMaterial: 'Terminación del piso', floorColor: 'Color del piso',
  parquet: 'Parquet de madera', slate: 'Pizarra', ivoryTile: 'Baldosa marfil', entryTile: 'Baldosa de entrada', concrete: 'Cemento',
  white: 'Tiza', cream: 'Lino', sand: 'Arena', sage: 'Salvia', blue: 'Gris azulado', clay: 'Arcilla',
  color: 'Color personalizado', mixed: 'Hay distintas terminaciones seleccionadas. El próximo cambio se aplica a todas las superficies seleccionadas.', reset: 'Restaurar original',
  doors: 'Puertas', door: 'Puerta', doorStyle: 'Tipo de puerta', panel: 'Panel opaco', glazed: 'Vidriada', passage: 'Paso abierto',
  doorColor: 'Terminación de la puerta', openness: 'Apertura de la puerta', closed: 'Cerrado', open: 'Abierto', noDoors: 'Esta variante no tiene puertas.',
  windows: 'Ventanas', window: 'Ventana', windowStyle: 'Tipo de ventana', casement: 'Batiente', sliding: 'Corrediza', fixed: 'Fija',
  frameColor: 'Color del marco', covering: 'Cortina o persiana', none: 'Ninguna', curtain: 'Cortinas', blind: 'Cortina enrollable', shutter: 'Persianas',
  coveringColor: 'Color de la tela o persiana', closure: 'Cierre de cortina o persiana', noWindows: 'Esta variante no tiene ventanas.',
  openingHint: 'Los estilos conservan las medidas de la abertura. Las cortinas y persianas también afectan la vista de luz natural.',
  naturalEnabled: 'Luz natural', artificialEnabled: 'Luces artificiales', lightingHint: 'Vista visual estimada. El brillo, los materiales y el paso de la luz no son mediciones calibradas.',
  fixedLights: 'Puntos de luz del ambiente', fixedLight: 'Punto de luz', lightRoom: 'Ambiente para la nueva luz', addLight: 'Añadir punto de luz', removeLight: 'Quitar punto de luz',
  chooseLight: 'Punto de luz a editar', noLights: 'Añadí un punto de luz en el techo, la pared u otra posición del ambiente.',
  lightName: 'Nombre de la luz', enabled: 'Luz encendida', temperature: 'Temperatura de color', brightness: 'Flujo luminoso', warm: 'Cálida', neutral: 'Blanca neutra', cool: 'Blanca fría',
  x: 'X (m)', y: 'Altura (m)', z: 'Z (m)', sourcePosition: 'Posición de la luz',
  fixtureLight: 'Luz de un objeto', selectFixture: 'Seleccioná una lámpara u otro objeto en el editor para añadir su fuente de luz.',
  emitLight: 'Este objeto emite luz', fixtureHint: 'Ubicá la fuente en la bombilla. Se mueve y gira junto con el objeto.',
  offsetX: 'X local (m)', offsetY: 'Altura desde la base (m)', offsetZ: 'Z local (m)',
  lightLimit: 'Hasta 8 fuentes de luz por distribución, incluidas las de los objetos.',
  saveHint: 'Cada distribución conserva sus propias terminaciones y luces. Guardá el proyecto para conservar los cambios.',
}
const fr: typeof en = {
  title: 'Finitions et éclairage', subtitle: 'Explorez l’ambiance de votre appartement.',
  materials: 'Murs et sols', openings: 'Portes et fenêtres', lighting: 'Éclairage',
  walls: 'Murs', wall: 'Mur', allWalls: 'Tous les murs', wallColor: 'Couleur du mur', exterior: 'Extérieur', interior: 'Intérieur',
  floors: 'Sols', floorRoom: 'Sol de la pièce', allRooms: 'Toutes les pièces', floorMaterial: 'Revêtement du sol', floorColor: 'Couleur du sol',
  parquet: 'Parquet en bois', slate: 'Ardoise', ivoryTile: 'Carrelage ivoire', entryTile: 'Carrelage d’entrée', concrete: 'Béton',
  white: 'Craie', cream: 'Lin', sand: 'Sable', sage: 'Sauge', blue: 'Bleu gris', clay: 'Argile',
  color: 'Couleur personnalisée', mixed: 'Plusieurs finitions sont sélectionnées. La prochaine modification s’applique à toutes les surfaces sélectionnées.', reset: 'Restaurer l’original',
  doors: 'Portes', door: 'Porte', doorStyle: 'Style de porte', panel: 'Panneau plein', glazed: 'Vitrée', passage: 'Passage libre',
  doorColor: 'Finition de la porte', openness: 'Ouverture de la porte', closed: 'Fermé', open: 'Ouvert', noDoors: 'Cette variante n’a pas de portes.',
  windows: 'Fenêtres', window: 'Fenêtre', windowStyle: 'Style de fenêtre', casement: 'À battants', sliding: 'Coulissante', fixed: 'Fixe',
  frameColor: 'Couleur du cadre', covering: 'Habillage de la fenêtre', none: 'Aucun', curtain: 'Rideaux', blind: 'Store enrouleur', shutter: 'Volets',
  coveringColor: 'Couleur du tissu ou du volet', closure: 'Fermeture de l’habillage', noWindows: 'Cette variante n’a pas de fenêtres.',
  openingHint: 'Les styles conservent les dimensions des ouvertures. L’habillage modifie aussi l’aperçu de la lumière naturelle.',
  naturalEnabled: 'Lumière naturelle', artificialEnabled: 'Lumières artificielles', lightingHint: 'Un aperçu visuel estimatif. La luminosité, les matériaux et la transmission de la lumière ne sont pas des mesures étalonnées.',
  fixedLights: 'Points lumineux de la pièce', fixedLight: 'Point lumineux', lightRoom: 'Pièce de la nouvelle lumière', addLight: 'Ajouter un point lumineux', removeLight: 'Retirer le point lumineux',
  chooseLight: 'Point lumineux à modifier', noLights: 'Ajoutez un point lumineux au plafond, au mur ou ailleurs dans la pièce.',
  lightName: 'Nom de la lumière', enabled: 'Lumière allumée', temperature: 'Température de couleur', brightness: 'Flux lumineux', warm: 'Chaude', neutral: 'Blanc neutre', cool: 'Blanc froid',
  x: 'X (m)', y: 'Hauteur (m)', z: 'Z (m)', sourcePosition: 'Position de la lumière',
  fixtureLight: 'Lumière d’un objet', selectFixture: 'Sélectionnez une lampe ou un autre objet dans l’éditeur pour ajouter sa source lumineuse.',
  emitLight: 'Cet objet émet de la lumière', fixtureHint: 'Placez la source au niveau de l’ampoule. Elle suit la position et la rotation de l’objet.',
  offsetX: 'X local (m)', offsetY: 'Hauteur depuis la base (m)', offsetZ: 'Z local (m)',
  lightLimit: 'Jusqu’à 8 sources lumineuses par agencement, y compris celles des objets.',
  saveHint: 'Chaque agencement conserve ses propres finitions et lumières. Enregistrez le projet pour conserver vos modifications.',
}
export const customizationCopy = { en, es, fr }
export type CustomizationCopy = typeof en
